### ISSUE TITLE
npm install fails due to wrong linebreaks [Windows 10 x64]

### ISSUE THREAD

**Issue by icl7126** [mozilla/webextension-polyfill#101]
Hello,
I just cloned this repository and executed `npm install` and I see the following error:

> $ npm install
> npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
> npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
> npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
> 
> > webextension-polyfill@0.2.1 prepublish C:\Users\Juraj\git\addons\webextension-polyfill
> > npm run build && npm run test
> 
> 
> > webextension-polyfill@0.2.1 build C:\Users\Juraj\git\addons\webextension-polyfill
> > grunt
> 
> Running "eslint:src" (eslint) task
> 
> C:\Users\Juraj\git\addons\webextension-polyfill\src\browser-polyfill.js
>     1:48   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
>   393:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
> 
> C:\Users\Juraj\git\addons\webextension-polyfill\Gruntfile.js
>     1:62   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
>   109:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
> 
> ✖ 502 problems (502 errors, 0 warnings)
>   502 errors, 0 warnings potentially fixable with the `--fix` option.
> 
> Warning: Task "eslint:src" failed. Use --force to continue.
> 
> Aborted due to warnings.

I would expect the build procedure to be platform independent.

**Comment by Rob--W** [comment]
Do you get the same issue when you download and unzip the zip archive?

If not, then I guess that this issue could be resolved by adding a `.gitattributes` file with the content

```
*.js text eol=lf
*.json text eol=lf
```
