### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by BoQsc** [mozilla/webextension-polyfill#107]
I have just started with **webextension-polyfill** on a **Chrome browser**:

1.  Downloaded **0.2.1** version of the **webextension-polyfill** 
**from:** https://github.com/mozilla/webextension-polyfill/releases
2.  Inserted **webextension-polyfill** `<script>` into **popup.html**, `<head>` element
**as noted in:** https://github.com/mozilla/webextension-polyfill#user-content-basic-setup
3. Got returned **an error** inside an **extension's console**: 

```
Uncaught ReferenceError: module is not defined
    at browser-polyfill.js:361
Uncaught TypeError: Cannot read property 'then' of undefined
    at popup.js:49
```

## popup.html

```
<!DOCTYPE html>
<html>
  <head>
    <script type="application/javascript" src="extension_addons/mdn_webextensions/browser-polyfill.js"></script>
    <style></style>
  </head>
  <body>
    <script src="popup.js"></script>
  </body>
</html>
```

**Comment by Rob--W** [comment]
Did you download the "Source code" release or the package from unpkg?

**Comment by BoQsc** [comment]
@Rob--W, I **have** downloaded the **"Source code"**.
**Haven't** tried the **package** from **unpkg** release

**Comment by Rob--W** [comment]
The "source code" should not be used as-is; you should use the (built) unpkg version instead.
