### ISSUE TITLE
In need of a quick small script snippet to check if the polyfill is working

### ISSUE THREAD

**Issue by BoQsc** [mozilla/webextension-polyfill#110]
I'm aware of [webextension-polyfill#examples](https://github.com/mozilla/webextension-polyfill#examples), but there is  a need to check if polyfill is working as expected with a small snippet that can be inserted anywhere inside any script and check the correctness either with console.log or any other way.

**Comment by Rob--W** [comment]
```javascript
if (typeof browser == 'object') {
  // It works!
}
```
