### ISSUE TITLE
Need help with message passing | no errors

### ISSUE THREAD

**Issue by BoQsc** [mozilla/webextension-polyfill#111]
Problem: I need to pass and get **"greeting"** message from and to **popup** and **content _script**, and I wonder what i'm missing, and why it is not working besides not giving me any errors.
Not a single  message is shown in neither side. What am I misunderstanding?

I have **popup.js** that is triggered when opening **browserAction**.
## popup.js (**browserAction**)
```
var requestCurrentTabId = {
  active:true,
  windowType:"normal",
  currentWindow: true
};


async function currentPage(){
  let getTabs = await browser.tabs.query(requestCurrentTabId);
  var activeTab = getTabs[0];

  await browser.tabs.executeScript(
    activeTab.id, {file:"content_scripts/chromeviewerpdf/insertSelectionListener.js"}
  );

  let connectToContentScript = await browser.tabs.connect(
    activeTab.id, {name: "content_script_port"}
  );


  connectToContentScript.postMessage({greeting: "Hi from the Extension popup"});
  connectToContentScript.onMessage.addListener(function(msg) {
    console.log("Got the message in the Popup: " + msg.greeting);
  }
  );
```
After opening **that popup.js**, you can see execution of the content script. 

 ```
 await browser.tabs.executeScript(
    activeTab.id, {file:"content_scripts/chromeviewerpdf/insertSelectionListener.js"}
  );
```

## insertSelectionListener.js (The content_script)

```
async function currentPage(){
  let connectToPopup = await browser.runtime.connect({name: "content_script_port"});
  connectToPopup.postMessage({greeting: "Hi from the Extension popup"});

  chrome.runtime.onConnect.addListener(function(port) {
    connectToPopup.onMessage.addListener(function(msg) {
      console.log("Got the message in the content_script: " + msg.greeting);
    });
  }
}
currentPage();

```

I need to send message from **browserAction (popup.js)** to **content_script (insertSelectionListener.js)** and send other message back.

**Comment by james-cnz** [comment]
Maybe connectToContentScript and connectToPopup need to be declared at the top level, to prevent them being garbage collected?
