### ISSUE TITLE
Polyfill the runtime.getBrowserInfo() function on browsers which don’t support it

### ISSUE THREAD

**Issue by ExE-Boss** [mozilla/webextension-polyfill#116]
The [`runtime.getBrowserInfo()` function](https://developer.mozilla.org/Add-ons/WebExtensions/API/runtime/getBrowserInfo) is [currently only supported in Firefox](https://developer.mozilla.org/Add-ons/WebExtensions/API/runtime/getBrowserInfo#Browser_compatibility).

Partial support for it can be added to other browsers by using user agent sniffing (I know, sniffing has horrible reputation) to extract the version and browser information.

User agent sniffing can be done in JavaScript using the [`useragent` package <img src="https://img.shields.io/npm/v/useragent.svg" alt="(on npm)" align="top"/>](https://www.npmjs.com/package/useragent) ([Test With RunKit](https://runkit.com/embed/apx79wofdew2)).

**Comment by ExE-Boss** [comment]
@lidel Fixed it 👍🏻.

**Comment by Rob--W** [comment]
The polyfill only offers access to APIs (via a nice Promise-based API) that exist in the browser. It does not provide polyfills for APIs that are missing from the platform: https://github.com/mozilla/webextension-polyfill#api-methods-or-options-that-are-only-available-when-running-in-firefox
