### ISSUE TITLE
browser.tabs.onCompleted.addListener unsupported?

### ISSUE THREAD

**Issue by helpermethod** [mozilla/webextension-polyfill#118]
Hi,

I've tried to port a Chrome extension to a Web Extension using this polyfill but it seems the  `tabs`API is only partially supported?

Are there any plans to add that functionality in the near future?

**Comment by Rob--W** [comment]
There is no `tabs.onCompleted` event. Did you mean [`tabs.onUpdated`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/onUpdated) or [`webNavigation.onCompleted`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation/onCompleted)?

**Comment by helpermethod** [comment]
Sorry was a problem with my build Tool configuration. Thanks for your great work!
