### ISSUE TITLE
changeInfo object in browser.tabs.onUpdated.addListener((tabId, changeInfo) is incomplete

### ISSUE THREAD

**Issue by helpermethod** [mozilla/webextension-polyfill#119]
According to the official [Mozilla docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/onUpdated#changeInfo), `changeInfo` should contain a bunch of additional properties, like `url` e.g..

But when I log the object, it seems to only contain a `status` property

Code in question:

```js
import browser from 'webextension-polyfill'

browser.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
  console.log(changeInfo) // changeInfo.url is never set
})
```

**Comment by Rob--W** [comment]
All of these properties are marked as optional.

In Chrome and Firefox (and other implementations), these properties are only set when they have changed. If you want to retrieve the URL, request the `"tabs"` permission and look at `tab.url`.
