### ISSUE TITLE
runtime.getURL(...) is not a function

### ISSUE THREAD

**Issue by marcofugaro** [mozilla/webextension-polyfill#123]
I am trying to import an image using [browser.runtime.getURL()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/getURL), however the extension is giving me this error:

<img width="818" alt="screen shot 2018-06-03 at 12 22 07" src="https://user-images.githubusercontent.com/7217420/40885561-fa622270-6728-11e8-9e2d-a9346ce3959d.png">

The file I'm importing it from is popup.js

**Comment by Rob--W** [comment]
Have you tried without webpack? Can you share a minimal project that reproduces the issue?

**Comment by aswan** [comment]
It is subtle, but that error message is not telling you that `runtime.getURL` is not a function, it is telling you that you called `runtime.getURL()` successfully then tried to use the return value as a function.  `runtime.getURL` returns a string so it sounds like a bug in your extension.

**Comment by rpl** [comment]
@aswan is right, the error message is actually related to a bug in the extension. Closing as invalid.
