### ISSUE TITLE
Chrome: "The message port closed before a response was received."

### ISSUE THREAD

**Issue by lydell** [mozilla/webextension-polyfill#130]
**Minimal repro repo:**
https://github.com/lydell/webextension-polyfill-messaging-issue

This happens with both v0.2.1 on npm and when built from commit 2537b23837d4752e3a6c3236c2776adbc89f1312.

# Summary

If a `browser.runtime.onMessage` callback does not return a Promise, `browser.runtime.sendMessage` will be rejected with the following error, causing noise in the console:

> "The message port closed before a response was received."

## Workaround

Even if you don't want to send a response, always return a promise
in your `onMessage` callback:

```js
// background.js
browser.runtime.onMessage.addListener(message => {
  console.log("background: onMessage", message);

  // Add this line:
  return Promise.resolve("Dummy response to keep the console quiet");
});
```

You can also make the `onMessage` callback `async` to implicitly return a Promise (resolving to `undefined` in the below example).

```js
// background.js
// Notice the `async` keyword.
browser.runtime.onMessage.addListener(async message => {
  console.log("background: onMessage", message);
});
```

# Files

Copied over for convenience from:
https://github.com/lydell/webextension-polyfill-messaging-issue

```json
{
  "manifest_version": 2,
  "version": "0.0.0",
  "name": "Test",
  "background": {
    "scripts": [
      "browser-polyfill-npm.js",
      "background.js"
    ]
  },
  "content_scripts": [
    {
      "matches": [
        "<all_urls>"
      ],
      "js": [
        "browser-polyfill-master.js",
        "content.js"
      ]
    }
  ]
}
```

```js
// background.js

browser.runtime.onMessage.addListener(onMessage);

function onMessage(message) {
  console.log("background: onMessage", message);

  // 1: Causes the following to be logged in content:
  // "The message port closed before a response was received."
  return undefined;

  // 2: Causes this response to be logged in content, as expected.
  // return Promise.resolve("response from background");

  // 3: Causes this error to be logged in content, as expected.
  // return Promise.reject(new Error("Could not respond"));

  // 4: Causes nothing at all to be logged in content!
  // I guess it is waiting for the deprecated `sendResponse` parameter to be
  // called.
  // return true;
}
```

```js
// content.js

// 1: Unless background returns a Promise in its onMessage, this promise is
// rejected with:
// "The message port closed before a response was received."
browser.runtime
  .sendMessage("hello from content")
  .then(console.log, console.error);



// 2: This does not seem to cause any errors:
// chrome.runtime.sendMessage("hello from content");
// console.log("content: after chrome.runtime.sendMessage", chrome.runtime.lastError);



// 3: Inside the callback, `chrome.runtime.lastError` will be:
// "The message port closed before a response was received."
// It seems like if `sendMessage` defines a callback but the other end doesn't
// respond, Chrome is treating that as an error. Which makes sense.
// The question is how this should be handled in a Promise based API.
// chrome.runtime.sendMessage("hello from content", response => {
//   console.log("content: callback", response, chrome.runtime.lastError);
// });
// console.log(
//   "content: after chrome.runtime.sendMessage with callback",
//   chrome.runtime.lastError
// );
```

## Solution?

Should the "The message port closed before a response was received." be detected, and the promise should be resolved with `undefined`?

**Comment by Rob--W** [comment]
Thanks for this report - I can confirm that this happens with and without `--enable-features=NativeCrxBindings` .

**Comment by sabrinasong** [comment]
What if the content script goes away after receiving the message, and cannot send a response?

**Comment by Rob--W** [comment]
> What if the content script goes away after receiving the message, and cannot send a response?

Then the `sendMessage` promise is rejected with an object with a "message" property.

In Firefox, the message is "Message manager disconnected"
In Chrome, the message is "The message port closed before a response was received."

**Comment by OussamaBATOUCHE** [comment]
hey , can some one give me simple solution

**Comment by prathmesh4** [comment]
Unchecked runtime.lastError: The message port closed before a response was received.
![error](https://user-images.githubusercontent.com/20142498/56015708-9b247700-5d17-11e9-90f6-4f1a7ee757f3.png)

**Comment by RobertJGabriel** [comment]
Add a return true. It will force chrome to wait for the response.

chrome.extension.onMessage.addListener((request, sender, sendResponse) => {
  // Look up a term from the dictionary using the Ajax API.
  const lookupURL = `http://dictionary-lookup.org/${request.arg}`;
  sendRequest(lookupURL)
    .then(resp => {
      sendResponse(resp || '{}');
    })
    .catch(error => {
      sendResponse('{}');
    });
  return true; // Inform Chrome that we will make a delayed sendResponse
});


example

**Comment by vrgomes** [comment]
i think that the: return true; // Inform Chrome that we will make a delayed sendResponse

Doesn't solve the issue.
Greetings.

**Comment by reZach** [comment]
@vrgomes  is correct, this fix does not work - is there another resolution to this issue?

**Comment by vrgomes** [comment]
Any updates on this?
Greetings.

**Comment by matthuhman** [comment]
Also curious about updates- I'm not sure if it has been happening before, but I've been spending time in the console recently and have seen this error pop up regularly since updating to the latest version of Chrome.

I'm currently running: Version 76.0.3809.132 (Official Build) (64-bit)

Thanks,
Matt

**Comment by reZach** [comment]
Using @RobertJGabriel 's answer as a place to start, I found the error occurs when we neglect to send a response at all. I found I needed to call `sendResponse` in addition to returning true to prevent the error from happening. It doesn't matter that the object we send is empty. @vrgomes hope this helps

```
chrome.runtime.onMessage.addListener(function(message, sender, sendResponse){
    // ..code
    sendResponse({});
    return true;
});
```

**Comment by stanleykayzz** [comment]
Hello, in my case I call sendResponse in my background.js then return true but like @vrgomes said are just delayed so the only difference is that I get error messages later in my background console.

**Comment by vrgomes** [comment]
> Using @RobertJGabriel 's answer as a place to start, I found the error occurs when we neglect to send a response at all. I found I needed to call `sendResponse` in addition to returning true to prevent the error from happening. It doesn't matter that the object we send is empty. @vrgomes hope this helps
> 
> ```
> chrome.runtime.onMessage.addListener(function(message, sender, sendResponse){
>     // ..code
>     sendResponse({});
>     return true;
> });
> ```

@reZach it looks like to work that way!
But had to put on the content script on all calls this check:
if(response == undefined || Object.keys(response).length == 0) return;

Greetings.

**Comment by reZach** [comment]
Yes, you will need that too @vrgomes. I forgot to put that in my reply.

**Comment by rpl** [comment]
@Deepansharora27 in the code snippet you pasted the onMessage listener is registered `chrome` global which is the one natively provided by chrome and not the polyfilled one and so your issue isn't actually related to the webextension-polyfill (and chrome doesn't support returning a response by returning a promise, you have to return `true` to let chrome know that the listener is going to reply asynchronously and then  call the response callback).

**Comment by Deepansharora27** [comment]
@rpl HIi , I am returning true as well but it isn't working for me

**Comment by rpl** [comment]
> @rpl HIi , I am returning true as well but it isn't working for me

I'm sorry but as I did mention in my previous comment yours isn't a polyfill issue, it is more likely an issue in how the extension is using the chrome APIs.

**Comment by superhipz** [comment]
I found why this error occur. Dont use async await in your code. Just use promise and return true at last. I fixed it after trying many time

**Comment by DrMalchev** [comment]
This works for me:
chrome.runtime.onMessage.addListener(async function (
  message,
  sender,
  sendResponse
) {
  console.log(message.data);
  sendResponse({ data: "Hey!" });
  return true;
});

**Comment by Rob--W** [comment]
> I am facing same issue, where I cannot disable chrome extensions as it is maintained by admin. Is there any way to get rid of this Issue.
> 
> Chrome: "The message port closed before a response was received."

That has nothing to do with the issue tracked here.

**Comment by Rob--W** [comment]
FYI to those who are following here - Chrome may at some point support `Promise` as return values in the `onMessage` listener (without requiring `return true`) - see https://bugs.chromium.org/p/chromium/issues/detail?id=1185241

**Comment by navidshad** [comment]
> https://bugs.chromium.org/p/chromium/issues/detail?id=1185241

This solution resolved my problem, try to do it and check if you did it right.

**Comment by navidshad** [comment]
> I found why this error occur. DONT USE **ASYNC AWAIT** in your code. Just use promise and return true at last. I fixed it after trying many time

This solution resolved my problem, try to do it and check if you did it right.

**Comment by rejoanahmed** [comment]
> I found why this error occur. DONT USE **ASYNC AWAIT** in your code. Just use promise and return true at last. I fixed it after trying many time

worked like a charm. I had async keyword which caused the issue. after removing everything works

**Comment by sfyang2** [comment]
> I found why this error occur. DONT USE **ASYNC AWAIT** in your code. Just use promise and return true at last. I fixed it after trying many time

你的答案是对的，我想应该是加了async后返回的是promoise对象而不是true，导致事件没有等待.

`
test("测试promise", () => {
        const onMessage = function (callback: () => any) {
            const res = callback()
           if(res===true)
             //进入正确的逻辑
            console.log('typeof', typeof res, `isPromise: ${(res instanceof Promise)}`,);
        }

        onMessage(() => {
            return true
        })

      //这样就导致了错误了
        onMessage(async () => {
            return true
        })
    })
`

**Comment by Njoxpy** [comment]
I was having the same issues. Someone told me that I should disable all the extensions I had installed. It worked, but the solution was not ideal!

**Comment by anaysah** [comment]
i am writing what i understood.

**background.js** 
```
chrome.runtime.onMessage.addListener(function (message, sender, sendResponse) {
    ...some code
    case "leaveRoom":
        socket.emit("leaveRoom", (response:boolean) => {
          console.log("background.js received leaveRoom message:", response);// just a console.log
          (response?room = undefined:null)   //not important for you
          sendResponse(response); //sends response when socket.emit is over
        });
        return true; //as the response is delayed due to socket request. it is important if any asyncronose code is their
        break;
    ...some code
}
```
As you can see, I have a case where I want to leave the room, which is on the backend server, so here `Socket.emit` is asynchronous.

**popup.js**
```
const leaveRoomMessage: DataOperationsMessage = {   //not important just a object for efficient code
      type: "DataOperations",
      action: "leaveRoom",
      from: "extension",
      to: ["background"]
};

chrome.runtime.sendMessage(leaveRoomMessage,async (response:boolean)=>{
      if(response){
        setRoom(undefined); //not important for you
        ...more code
      }
});
```

So, let me explain my scenario first. I have a button that leaves a Room. When I click on it, it sends a request to the background file, then the background file sends a request to the backend server.

Now, since `socket.emit` is asynchronous, it will take time, but `chrome.runtime.onMessage.addListener(function` will not wait for it and will complete its execution. When `socket.emit` is resolved, it will try to fire `sendResponse`, but as that listener is already closed, it will not be able to sendResponse and will show this error: **'Unchecked runtime.lastError: The message port closed before a response was received.'**

Learning: If your code has an async function that takes time to complete, please use `return true` at the end to let the listener know to wait for its execution.
