### ISSUE TITLE
Error in invocation of downloads.show and downloads.open

### ISSUE THREAD

**Issue by KBoyarchuk** [mozilla/webextension-polyfill#138]
![image](https://user-images.githubusercontent.com/8619550/41858806-6bbe4bac-78a3-11e8-91dc-a41aab62cd13.png)

Although writing in this way `window.chrome.downloads.show(id);` does not cause any problems.

**Comment by Rob--W** [comment]
This will be fixed in the next version; on the master branch it has been fixed by 597788817e599b5356b9988d0c7a40ea6d953f58.

**Comment by KBoyarchuk** [comment]
When the new version will be available?

**Comment by Rob--W** [comment]
(The next version is 0.3.0, and #88 will be closed when a new version is published.)

**Comment by Rob--W** [comment]
0.3.0 has been published: https://github.com/mozilla/webextension-polyfill/releases/tag/0.3.0
