### ISSUE TITLE
ESLint causes build on windows to fail with default git settings

### ISSUE THREAD

**Issue by rmtmckenzie** [mozilla/webextension-polyfill#14]
Because ESLINT is set to need linefeeds set to LF, by default on windows building this will fail.

There's a few possible workarounds - the easiest being setting global git config core.autocrlf to force linefeeds to LF. However, this can break other programs' builds. A local git config can also be used but that doesn't help if using NPM to pull this repo.

I'm going to do a pull request for adding a .gitattributes file which forces line feeds to LF regardless of the git config for *.js files in the repo.

**Comment by T-vK** [comment]
All you need to do is edit the .eslintrc file. Change `"linebreak-style": [2, "unix"],` to `"linebreak-style": [2, "windows"],` when you are on Windows.

**Comment by Rob--W** [comment]
This was fixed by #103.
