### ISSUE TITLE
Document how to use webextension-polyfill with webpack.ProvidePlugin

### ISSUE THREAD

**Issue by Rob--W** [mozilla/webextension-polyfill#156]
There is some confusion over how the polyfill can be used with `webpack.ProvidePlugin`

We should figure out the recommended way to do so and document it, in the README.

Here is some discussion: https://github.com/mozilla/webextension-polyfill/pull/86

**Comment by Rob--W** [comment]
@Morikko Thanks for sharing. That approach looks very reasonable. The only "downside" is that you have to add an include everywhere in your extension, but the upside is that there is no duplication of polyfill code when your extension has multiple bundles for all parts (e.g. content script, background page, options page, popup, etc.).

**Comment by bfred-it** [comment]
For the record we also use [that method in Refined GitHub](https://github.com/sindresorhus/refined-github/blob/673b90073e3a030d24f0485c8a457b4452c643c8/webpack.config.js#L37-L50)

But the config is shorter:

```js
	plugins: [
		new CopyWebpackPlugin([
			{
				from: 'node_modules/webextension-polyfill/dist/browser-polyfill.min.js'
			}
		])
	],
```

**Comment by glacambre** [comment]
For those who would really prefer using webpack's Provide plugin, you can do so by installing webpack's import loader (e.g. `npm install imports-loader`) and then using it to make sure `browser` is undefined when loading webextension-polyfill:
```javascript
module: {
      rules: [{
        test: require.resolve('webextension-polyfill'),
        use: 'imports-loader?browser=>undefined'
      }]
},
plugins: [
  new ProvidePlugin({
    "browser": "webextension-polyfill"
  })
]
```

**Comment by fregante** [comment]
Note: version 0.9.0 supports `ProvidePlugin` now thanks to #351 

```js
plugins: [
  new ProvidePlugin({
    browser: "webextension-polyfill"
  })
]
```

**Comment by saptarshimondal** [comment]
Working with webpack v5.73.0 and webextension-polyfill v0.9.0. Thank you. 


> Note: version 0.9.0 supports `ProvidePlugin` now thanks to #351
> 
> ```js
> plugins: [
>   new ProvidePlugin({
>     browser: "webextension-polyfill"
>   })
> ]
> ```
