### ISSUE TITLE
system.display.{getInfo, getDisplayLayout} are not polyfilled

### ISSUE THREAD

**Issue by indigoviolet** [mozilla/webextension-polyfill#158]
These do take callbacks (https://developer.chrome.com/apps/system_display)

**Comment by Rob--W** [comment]
The `chrome.system` APIs are not part of the WebExtensions API, and therefore not polyfilled:
https://github.com/mozilla/webextension-polyfill#no-promise-returned-on-chrome-for-some-api-methods

**Comment by indigoviolet** [comment]
Thank you for the quick response! I wasn't sure if this was a bug or expected behavior.

Is https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions the authoritative listing of the WebExtensions API? It might be useful to link to this in the docs.
