### ISSUE TITLE
browser.runtime.onMessage does not receive messages sent using chrome.runtime.sendMessage from other sites

### ISSUE THREAD

**Issue by ibc** [mozilla/webextension-polyfill#159]
### Scenario

* Chrome browser.

* Browser extension made with `webextension-polyfill` whose background file listens for requests:

```js
browser.runtime.onMessage.addListener((request, sender) =>
{
	console.warn('request received [method:%s]', request.method);
});
```

* It properly receives requests sent from the content or popup scripts:

```js
browser.runtime.sendMessage({ method: 'hello' });
// or
chrome.runtime.sendMessage(EXTENSION_ID, { method: 'hello' });

// It prints in the background console:
// => request received [method:hello]
```

* However, it does not receive those requests from other web sites (of course, `externally_connectable` includes that web site domain). Requests are sent using the `chrome.runtime.sendMessage` API as above.

Now the interesting thing:

If I change the `background.js` file to this one, requests **are** received from the other web site:

```js
chrome.runtime.onMessageExternal.addListener((request, sender, sendResponse) =>
{
  console.warn('request received [method:%s]', request.method);
});
```

This is:

* If `background.js` uses the `chrome` based API and the external web site too, the external web site can send requests to the extension.
* If `background.js` uses the `browser` based API (with this polyfill) and the external web site uses the `chrome` based API, the external web site CANNOT send requests to the extension.

**Comment by Rob--W** [comment]
This does not look like a bug in the polyfill.

`browser.runtime.onMessage` and `chrome.runtime.onMessage` will only receive messages sent internally by the extension.

the `onMessageExternal` event should be used to handle messages from potentially untrusted (external) sources.

**Comment by ibc** [comment]
oh, sorry, my fault!!! Let me please test that using the **proper** `onMessageExternal` does work and I'll close the issue. Sorry!

**Comment by ibc** [comment]
It works perfectly. Sorry, I just didn't realize I was using `onMessage` instead of `onMessageExternal`. I wrongly understood that the standard `browser.runtime` API become just `onMessage`.

Thanks a lot.
