### ISSUE TITLE
On-demand content script inject

### ISSUE THREAD

**Issue by Stormsher** [mozilla/webextension-polyfill#164]
How about browser.contentScripts.register support? Seems like it similar to chrome declarative content API. Or are there any similar ways to inject content script on some conditions?

**Comment by Rob--W** [comment]
> This library does not provide any polyfill for API methods and options that are only available on Firefox, and they are actually considered out of the scope of this library.

( https://github.com/mozilla/webextension-polyfill#api-methods-or-options-that-are-only-available-when-running-in-firefox )

Even if we wanted to, neither Chrome's declarativeContent API, nor tabs.executeScript can be used to polyfill the contentScripts.register API.

**Comment by bfred-it** [comment]
@Rob--W I'd like your opinion on https://github.com/bfred-it/content-scripts-register-polyfill

I had initially used `declarativeContent` (https://github.com/sindresorhus/refined-github/pull/2111/files#diff-21cb92a99a8fa8709f3e4d41b5799523R42) but it had some [trouble with CSS](https://github.com/sindresorhus/refined-github/issues/2174#issuecomment-505243727) (I later saw your comment about it on bugzilla) and then [later](https://github.com/sindresorhus/refined-github/pull/2181/files#diff-21cb92a99a8fa8709f3e4d41b5799523R65) changed it to a regular `executeScript`/`insertCSS`.

It seems to work correctly now and if you have Refined GitHub you've been using the code for a few days already.

Fun part: `webextension-polyfill` automatically enables `browser.contentScript.register` by detecting and extending `chrome.contentScript.register`
