### ISSUE TITLE
browser.devtools.inspectedWindow.eval() resolves with incorrect promise signature

### ISSUE THREAD

**Issue by keithclark** [mozilla/webextension-polyfill#168]
When calling `browser.devtools.inspectedWindow.eval()` in Chrome (I'm using 71), the resulting promise appears to resolve with an incorrect signature. According to [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.inspectedWindow/eval#Return_value), the resulting promise should be an array containing two elements:

> A Promise that will be fulfilled with an array containing two elements.
>
>If no error occurred, element 0 will contain the result of evaluating the expression, and element 1 will be undefined.
>
>If an error occurred, element 0 will be undefined, and element 1 will contain an object giving details about the error. Two different sorts of errors are distinguished

However, running the following script

```js
let statement = `Array.from(document.querySelectorAll('*')).map(e=>e.tagName)`;
browser.devtools.inspectedWindow.eval(statement).then(console.log);
```

Returns

```js
["HTML", "HEAD", "META", ...]
```

I was expecting

```js
[
  ["HTML", "HEAD", "META", ...],
  undefined
]
```

If I call the same function with a statement that will throw an error, the promise resolves with the correct error signature:

```js
let statement = `%%%`;
browser.devtools.inspectedWindow.eval(statement).then(console.log);
```

Returns:

```js
[
  undefined,
  {
    isException: true,
    value: "SyntaxError: Unexpected token %"
  }
]
```

Firefox behaves as expected.

**Comment by Rob--W** [comment]
Chrome's devtools API implementation is not implemented using the default extension bindings. The implementation is here, and contrary to [Chrome's documentation](https://developer.chrome.com/extensions/devtools_inspectedWindow#property-eval-callback), there are not always two parameters passed to the callback: https://chromium.googlesource.com/chromium/src/+/10e9b59ba1acc764a058b8d152e3825ff7db50ba/third_party/blink/renderer/devtools/front_end/extensions/ExtensionAPI.js#577

I suppose that we could repurpose [`singleCallbackArg` in our polyfill](https://github.com/mozilla/webextension-polyfill/blob/34a6ab45595dd2c73130f2d9893452f6aa622d85/src/browser-polyfill.js#L95), so that:

- true = force single value (=current implementation)
- unset = array or single value depending on number of arguments (=current implementation)
- false = force array (=new behavior, to fix this bug).

**Comment by keithclark** [comment]
If I understand the Chromium source correctly, the 2nd parameter isn't passed in the event of an error. I guess that's not really an issue for the event hander as omitting the 2nd argument would still result in  value of `undefined` when trying to access element `[1]` of the array.

Repurposing `singleCallbackArg` as you suggested would work.

Just a suggestion: Would it make the code easier to understand if you used string values instead? Something like:

* `single` = force single value (=current implementation)
* `auto` = array or single value depending on number of arguments (=current implementation)
* `array` = force array (=new behavior, to fix this bug).

**Comment by frehner** [comment]
Currently doing 
```js
  try {
    const browserInfo = await browser.runtime.getBrowserInfo()
  } catch (err) {
    // this is a hacky way to check to see if we're in Chrome or Firefox; currently only Firefox has this API, and Chrome throws an error if you try to call it.
    // and we have to do this until this commit https://github.com/mozilla/webextension-polyfill/commit/6f178c56daed2f548d29e879e3caf082183eed3a is released
    return result
  }
  return result[0];
```
until this is released if anyone needs a workaround :)

**Comment by rpl** [comment]
> Any idea on when the next release is so I can use it?

@frehner we just [released this fix on npm](https://www.npmjs.com/package/webextension-polyfill) as part of the new [webextension-polyfill 0.4.0](https://github.com/mozilla/webextension-polyfill/releases/tag/0.4.0) version.

**Comment by joelstransky** [comment]
I'm confused. How are you calling `browser.devtools.inspectedWindow.eval()` in chrome when in chrome it's `chrome.devtools.inspectedWindow.eval()`. Also, how is this relevant if chrome's eval doesn't even return a promise?

**Comment by Rob--W** [comment]
@joelstransky This project (webextension-polyfill) provides a `browser` namespace to environments without such an environment, which provides promisified methods for APIs that are known to have a callback. `devtools.inspectedWindow.eval` is such an API. See this project's README for more details.
