### ISSUE TITLE
Send error stack with error message

### ISSUE THREAD

**Issue by davestewart** [mozilla/webextension-polyfill#173]
I've written a rather robust service bus mechanism that handles registering services, sending messages, converting data, calling services, and even nicely reporting errors (for both sides) but one thing is missing - returning the stack trace of the receiving end when there's an error, so the developer can see **where** in the code things didn't work, rather than just **what**.

It seems this would be really easy to add:

https://github.com/mozilla/webextension-polyfill/blob/master/src/browser-polyfill.js#L411-L422

Is the project accepting pull requests?

**Comment by Rob--W** [comment]
The polyfill is no-op in Firefox. Also in Firefox, the stack trace is not included when errors are returned to the message sender.

If you want to include the stack everywhere, then it should be encoded in the message format of your message bus.

**Comment by davestewart** [comment]
> The polyfill is no-op in Firefox.

I completely didn't think of that!

Great idea to encode the stack into the message. I presume everything will need to go through another try/catch; I'll try this.

Thanks!
