### ISSUE TITLE
Promise rejection and errors

### ISSUE THREAD

**Issue by sergey-shpak** [mozilla/webextension-polyfill#179]
Getting `Error: An unexpected error occurred` instead of real rejection reason

```javascript
// content script
browser.runtime.onMessage.addListener(() => 
  Promise.reject({ some: 'reason' }))
```
```javascript
// background script
browser.tabs.sendMessage(<tabId>, true)
  .catch(reason => console.log(reason))
```

**Comment by Rob--W** [comment]
This is expected. Error objects are generally non-serializable, and the message is only provided for debugging purposes. If you run the same code in Firefox, then you will get `Error: "undefined"` (because the `message` property is missing).

**Comment by rpl** [comment]
Closing because the behavior is expected as @Rob--W pointed out.
