### ISSUE TITLE
browser-polyfill.min.js not working with Chrome

### ISSUE THREAD

**Issue by joncu01** [mozilla/webextension-polyfill#18]
When I use the non-minified version in /dist my extension works fine.  When I switch out to use browser-polyfill.min.js instead, I get the following errors:

Uncaught SyntaxError: Unexpected token {              browser-polyfill.min.js:18

The minified version seems to have a problem?  Anyone else seeing this?

**Comment by rpl** [comment]
@joncu01 the same SyntaxError issue has been reported in #10, it seems to be an issue with the minification of some of the ES6 syntaxes used in the sources, I've opened #11 (which has not been merged yet) to use [babili](https://github.com/babel/babili) as a ES6-aware minifier, can you give a try to the version in #11 and confirm that the changes applied from that pull request solve this issue for you?

**Comment by joncu01** [comment]
@rpl - thanks that worked!

**Comment by rpl** [comment]
@joncu01 Thanks again for reporting this issue, I'm now closing it as fixed (by #11).
