### ISSUE TITLE
pageCapture namespace for chrome isn't included

### ISSUE THREAD

**Issue by mchusovlianov** [mozilla/webextension-polyfill#180]
I can't find pageCapture namespace here -  https://github.com/mozilla/webextension-polyfill/blob/master/api-metadata.json and it doesn't work for me now. Is it possible to support this namespace?

**Comment by Rob--W** [comment]
The pageCapture API is only supported by Chrome, hence the polyfill does not wrap the API, as only APIs that are supported by Firefox and Chrome are part of the polyfill - see
https://github.com/mozilla/webextension-polyfill#no-promise-returned-on-chrome-for-some-api-methods

If Firefox ever adds [support for saving as MHTML](https://bugzilla.mozilla.org/show_bug.cgi?id=1261339), then we can reconsider adding the namespace to the polyfill.
