### ISSUE TITLE
runtime.getBrowserInfo() should not be in api-metadata.json

### ISSUE THREAD

**Issue by rafael-gssa** [mozilla/webextension-polyfill#184]
This method is not supported on Chrome.

Apparently it was already supposed to be removed in https://github.com/mozilla/webextension-polyfill/pull/125?

**Comment by Rob--W** [comment]
The diff in #125 shows the difference between what would be generated if only supported methods are used. The red parts of the div haven't actually been removed, but pull requests to remove them are welcome.

**Comment by caitmuenster** [comment]
Mentor: @Rob--W 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by Shubhamchinda** [comment]
Hey, Can I take this up?

**Comment by Rob--W** [comment]
@Shubhamchinda  Sure. Let me know if you have any questions.

**Comment by rafaelgssa** [comment]
@Shubhamchinda Thanks for the fix, I never got around to doing it.

@Rob--W Is a new release coming soon? Right now I'm having to manually remove this line when using the NPM package.

**Comment by Rob--W** [comment]
I'll check whether we can create a new release, on Thursday.
