### ISSUE TITLE
Inclusion in Firefox throws a console error

### ISSUE THREAD

**Issue by blimmer** [mozilla/webextension-polyfill#186]
Including the polyfill on Firefox throws an error. It does not need to polyfill for Firefox, but I expected its inclusion to not throw an exception.

### The error
```console
ReferenceError: chrome is not defined
```

### The HTML

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="text/javascript" src="https://unpkg.com/webextension-polyfill@0.4.0/dist/browser-polyfill.js"></script>
  </head>
  <body>
  </body>
</html>
```

### Screenshot
<img width="1067" alt="Screen Shot 2019-05-10 at 16 18 05" src="https://user-images.githubusercontent.com/630449/57559567-b5b23600-733f-11e9-94ba-b08e041e31e8.png">

**Comment by blimmer** [comment]
Also, you can reproduce this by opening `webextension-polyfill/test/fixtures/devtools-extension/devtools_page.html` in Firefox within this project.

**Comment by Rob--W** [comment]
Do not include the polyfill in a web page, then you won't get this error.

For more details, see my previous replies to https://github.com/mozilla/webextension-polyfill/issues/98

**Comment by blimmer** [comment]
What do you think about a more user-friendly error message when people inevitably think they can include it on a web page? That might help drive inline documentation of this design decision.

**Comment by rudevich** [comment]
But is simple include should cause an error?

**Comment by Rob--W** [comment]
I'm still not entirely convinced that we need to do this, but I submitted a PR at #190 to explore our options.
