### ISSUE TITLE
notifications.update()

### ISSUE THREAD

**Issue by wbobeirne** [mozilla/webextension-polyfill#191]
Currently there's no polyfill for [`notifications.update()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/update), presumably because FireFox doesn't support it. Perhaps a good polyfill would be to provide it, and if the browser doesn't support `notifications.update()`, just run `notifications.clear()` followed by a new `notifications.create()` with the id passed.

**Comment by rpl** [comment]
The `notifications.update` method is polyfilled as expected when running on chrome.
This polyfill is a nop when running in Firefox and as pointed out in the ["API methods or options that are only available when running in Firefox" section of the readme](https://github.com/mozilla/webextension-polyfill#api-methods-or-options-that-are-only-available-when-running-in-firefox) polyfilling missing functionalities in Firefox is out of scope for this project.

The extension can detect at runtime if `notification.update` is available or not and polyfill the missing API method on its own.
