### ISSUE TITLE
executeScript always returns true

### ISSUE THREAD

**Issue by davidb1** [mozilla/webextension-polyfill#192]
I'm trying to check if a content script has run in chrome:

in background code:
```
browser.tabs
      .executeScript(tabId, { file: "/static/js/content.js" })
      .then(results => {
        console.log(results);
})
```

content.js
```
(function() {
  if (window.hasRun) {
    return true;
  }
  window.hasRun = true;
})();
```

If I write to console the output of content.js I get `undefined` yet when I look in results it is always an array with true as the script's result. The first script run should be undefined and each after should be true yet it's not what's happening

**Comment by Rob--W** [comment]
This is expected - [the return value of `browser.tabs.executeScript`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript#Return_value) is always an array (or an error, e.g. if you don't have enough permissions).

**Comment by davidb1** [comment]
@Rob--W I do get an array, but the result in the array should be `undefined` and not `true`

**Comment by Rob--W** [comment]
In your code, the result of the should only be `undefined` at the first execution.
When you repeat the invocation again, the result is expected to be `true`.

**Comment by davidb1** [comment]
I know and that is what I wrote, but the result is always true instead of being undefined and then always true.

**Comment by Rob--W** [comment]
The polyfill doesn't grab `true` out of thin air. If you see `true`, then the most likely explanation is that you've already run the script once.

Consider adding logging to see when the script executes. If you can still reproduce the problem despite the script running once, please provide an example of your project and the Firefox version that you are using.

**Comment by davidb1** [comment]
I have checked this multiple times, every first run it was still `true` instead of `undefined`. This is from running `executeScript` from a background script
