### ISSUE TITLE
chrome.proxy.onError is not working in chrome

### ISSUE THREAD

**Issue by maximtop** [mozilla/webextension-polyfill#195]
Hi, guys. 
Could you please make possible to use onError event listener in the Crome as well? 

![image](https://user-images.githubusercontent.com/17272769/61885409-76d75980-af06-11e9-9228-c3a65ab07c98.png)

**Comment by Rob--W** [comment]
Chrome's proxy API and Firefox's proxy API are completely different. What are you expecting to happen from a polyfill?

**Comment by maximtop** [comment]
Thank you. I got you. Sorry for bothering.

**Comment by da2x** [comment]
You mean chrome.proxy.onProxyErrorr!
