### ISSUE TITLE
Provide dist files at a static url for people to download without building

### ISSUE THREAD

**Issue by wagnerand** [mozilla/webextension-polyfill#20]
Although not strictly necessary for Firefox, I have seen the polyfill being used in webextensions. And I think it's reasonable to do so. Developers want to have as few differences as possible between the chrome and the firefox version of their add-on.

We could save developers and reviewers some time (and possible mistakes), if authoritative dist files would be available for people to download and use. Our validation tools can verify the checksum and mark the files as _trusted_ automatically during review.

Developers don't need to build the polyfill.
Reviewers don't need to review it.
Everybody wins. 🎉

**Comment by josephfrazier** [comment]
Now that the polyfill is published to npm (https://github.com/mozilla/webextension-polyfill/pull/36), it is available from the https://unpkg.com CDN at https://unpkg.com/webextension-polyfill@0.1.1

**Comment by wagnerand** [comment]
That's great! I guess we can close this now.

**Comment by rpl** [comment]
@wagnerand definitely!

Thanks @josephfrazier!
