### ISSUE TITLE
How to allow `<all_urls>` optional permission

### ISSUE THREAD

**Issue by Manvel** [mozilla/webextension-polyfill#206]
I'm having trouble testing additional permission request of my extension.

The following is set as optional permission in the `manifest.json` file:
```
"optional_permissions": ["<all_urls>"],
```

And in the extension I do request and revoke the permission using:
```
chrome.permissions.request({"origins": ["<all_urls>"]}) // Request
chrome.permissions.remove({"origins": ["<all_urls>"]}); // Revoke
```

I would like to be able to test the extension behavior when permission is successfully requested and revoked, but there seem to be no way to fetch permission `dialog` event and accept, also it doesn't seem to be possible to do using `browserContext.overridePermissions `.

Any idea how that can be done?

**Comment by Rob--W** [comment]
How does this question relate to this project / repository?

**Comment by Manvel** [comment]
It is not, apologies 🤦‍♂ I thought I have opened this issue in https://github.com/GoogleChrome/puppeteer. Feel free to delete it.
