### ISSUE TITLE
Error when using browser.runtime.sendMessage(): "Uncaught (in promise) TypeError, no matching signature"

### ISSUE THREAD

**Issue by mikecrittenden** [mozilla/webextension-polyfill#215]
I have the following code in my contentscript.js:

```
browser.runtime.sendMessage({hello: 'goodbye'}, function (response) {
    console.log(response);
});
```

That gives me this error in Chrome:

```
contentscript.js:2300 Uncaught (in promise) TypeError: Error in invocation of runtime.sendMessage(optional string extensionId, any message, optional object options, optional function responseCallback): No matching signature.
```

The actual stack trace tracks it down to this section in the compiled JS: 

```
        return new Promise((resolve, reject) => {
          const wrappedCb = wrappedSendMessageCallback.bind(null, { resolve, reject });
          args.push(wrappedCb);
          apiNamespaceObj.sendMessage(...args);
        });
```

And here's the value of `args` there:

![image](https://user-images.githubusercontent.com/32261/71038628-3dd79580-20f0-11ea-936f-a5a3982879f4.png)

Any idea what's going on here? This is such a minimal example that I feel like I must be doing something totally dumb.

**Comment by Rob--W** [comment]
You cannot use extension APIs from a regular web page. In Chrome, web pages may have access to the `chrome.runtime.sendMessage` method as part of the external messaging API. That's why the error message complains about the method signature instead of the absence of the method.

**Comment by mikecrittenden** [comment]
@Rob--W Heya, thanks for the quick reply! This is a fantastic project and I really appreciate all the work you and others have put into it. 

> You cannot use extension APIs from a regular web page

I'm not, though. I'm running `browser.runtime.sendMessage()` from an extension's content script to pass a message to the same extension's background.js where it is received. This is one of the primary use cases for `sendMessage()` as far as I know? Apologies if I misunderstood your point. 

Note that changing the `browser.runtime` to `chrome.runtime` works fine because that avoids the `wrappedSendMessageCallback` stuff which seems to be the place where things are going wrong, so I think in general I'm not doing anything that shouldn't work.

**Comment by Rob--W** [comment]
Does it work if you use `browser.runtime.sendMessage({hello: 'goodbye'}).then(function (response) {`  instead of callbacks?

**Comment by mikecrittenden** [comment]
That worked! You're the best, thanks @Rob--W! 🎉

**Comment by ZdravkoJovanovic** [comment]
For anyone having this error, check your current tabID, before sending your variable to your content script, get your tabID and than send your data.
