### ISSUE TITLE
How to make it work with sinon-chrome in tests

### ISSUE THREAD

**Issue by dsrini-open** [mozilla/webextension-polyfill#218]
With the Fix 190 [https://github.com/mozilla/webextension-polyfill/pull/190], the polyfill does not work on outside extension context.
What about the tests? Have imported in each page in source files using - 
`import browser from "webextension-polyfill";`
which is causing the tests to fail with -

> Error: This script should only be loaded in a browser extension.

**Comment by Rob--W** [comment]
How are you running tests?

**Comment by dsrini-open** [comment]
@Rob--W
Through mocha. 

Meanwhile the workaround that I found is the following - 
```
  if (!chrome.runtime) chrome.runtime = {};
  if (!chrome.runtime.id) chrome.runtime.id = "history-delete";
```
Having this in the setup.js file, running it first before everything works.

**Comment by Rob--W** [comment]
Just `chrome.runtime.id = "testid";` should be sufficient. [sinon-chrome](https://github.com/acvetkov/sinon-chrome) does declare a `chrome.runtime.id` property, but its value is `null`, which caused the duck-typing to fail.
