### ISSUE TITLE
tabs.lastAccessed is missing

### ISSUE THREAD

**Issue by ObliviousParadigm** [mozilla/webextension-polyfill#223]
Can I work on this? I don't know how to start but I would love to work on this with some help.

**Comment by Rob--W** [comment]
This information is not provided in Chrome's extension API.

This polyfill does not provide missing functionality, it merely offers a promise-based API for extensions in Chrome and Firefox.

**Comment by ObliviousParadigm** [comment]
Oh yeah! My bad. I forgot about that
