### ISSUE TITLE
ReferenceError: global & process is not defined

### ISSUE THREAD

**Issue by Mrshulan** [mozilla/webextension-polyfill#226]
Recently, I used "webextension-polyfill": "^ 0.6.0", and the browser extension was used as a packaging solution.
I found that in the latest update of chrome (81+), the process and global variables will appear. Error: is not defined
![image](https://user-images.githubusercontent.com/38124644/79454267-7bf0b180-801d-11ea-84c5-9a1158499859.png)
![image](https://user-images.githubusercontent.com/38124644/79454334-9aef4380-801d-11ea-8253-2a43f4a762cf.png)

**Comment by Rob--W** [comment]
This is not an issue with `web-ext`, but with your build configuration.

**Comment by Mrshulan** [comment]
yep, thanks, my configuration is wrong
