### ISSUE TITLE
No underlying prototype for wrapped event handlers

### ISSUE THREAD

**Issue by spaceribs** [mozilla/webextension-polyfill#227]
Good morning,

I'm currently looking into the following feature PR for Zone.js to support listening to extension events and monkeypatching them: https://github.com/angular/angular/pull/36599

You can see theres a lot of events I plan on patching! Part of the issue seems to be the approach this polyfill has taken in wrapping `{ addListener, removeListener, hasListener }`, there doesn't seem to be any underlying prototype meaning each and every event emitter needs to be patched separately.

Do you think it would be wise for me or some other contributor to start by creating that underlying prototype here for all wrapped events?

**Comment by Rob--W** [comment]
There is no prototype for extension API objects.

For example every part of the extension APIs in Firefox are unique objects, not derived from any prototype. The property values are currently lazily initialized as well, so you should ideally try to avoid accessing the values of the extension API namespace until the extension actually needs it. This behavior will likely change in the future, but it is not something that you can nor should rely on.

To reliably overwrite APIs without side effects, use Proxies (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy). This polyfill also uses Proxy, so you can take a look at its source for inspiration.

**Comment by spaceribs** [comment]
Ah, I didn't realize this polyfill skips itself if the browser object already exists! I'm used to polyfills being greedy :)

Thanks for the pointer towards proxies, I'm looking forward to getting web extensions fully supported by Angular in the coming weeks. While there are a bunch of examples of other zone.js patches (bluebird, socket-io), the patches are a tad on the older side, more than likely to allow Zone.js to work without an additional polyfill for IE11.
