### ISSUE TITLE
Provide releases in `dist` folder or similar

### ISSUE THREAD

**Issue by mcongrove** [mozilla/webextension-polyfill#237]
Mozilla's docs on publishing extensions says that any third-party libraries must be documented in submissions to AMO. Specifically, it says to provide a link to the distributed code that is tagged as a release, _not_ from a CDN. See here: https://extensionworkshop.com/documentation/publish/third-party-library-usage/#how-to-determine-the-third-party-library-link

It would be helpful to have this package comply with those requirements.

**Comment by Rob--W** [comment]
You can link to https://github.com/mozilla/webextension-polyfill/releases , which features a link to unpkg.com, which in turn retrieves the file directly from the package that has been publshed on npm: https://www.npmjs.com/package/webextension-polyfill?activeTab=versions

These URLs are stable and should suffice for AMO. In contrast, the examples in [the documentation that you've linked](https://extensionworkshop.com/documentation/publish/third-party-library-usage/#how-to-determine-the-third-party-library-link) refer to an unversioned version of a library, whose content may change at any point in time.

**Comment by mcongrove** [comment]
👍
