### ISSUE TITLE
Missing "menus" polyfill for the "contextMenus"?

### ISSUE THREAD

**Issue by Juraj-Masiar** [mozilla/webextension-polyfill#242]
I'm now building addon for Firefox, Chrome **AND** Thunderbird and while before I could just use ["contextMenus" API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus) in both Firefox and Chrome, now if I want to support Thunderbird as well I can't use it [because it's not there, there is only "menus" API](https://thunderbird-webextensions.readthedocs.io/en/78/menus.html).

So I've been thinking, why is the `browser.menus` not polyfilled here for Chrome? 
If I'm right, all that needs to be done is something like this:
```javascript
if (IS_CHROME) {
  browser.menus = browser.contextMenus;
}
```
Right? :)

**Comment by Rob--W** [comment]
The `menus` API is a superset of the `contextMenus` API in terms of functionality, which means that `contextMenus` has less functionality compared to `menus` :

- `tools_menu` context type.
- `menus.getTargetElement` and `info.targetElementId`.

In practice you can use `browser.contextMenus` when `browser.menus` is unavailable.

**Comment by Juraj-Masiar** [comment]
But there are browser specific features in every namespace, not just with context menus. So why not unite them under one? It would help users with cross browser implementations.

**Comment by Rob--W** [comment]
I suppose that this is one of the few APIs where we could consider aliasing the namespace, despite https://github.com/mozilla/webextension-polyfill#api-methods-or-options-that-are-only-available-when-running-in-firefox

I'll discuss this at the next triage meeting.

**Comment by Rob--W** [comment]
We've discussed this, and we have decided to not add this, with the same reasoning as in https://github.com/mozilla/webextension-polyfill/issues/74

**Comment by Rob--W** [comment]
That is covered by https://github.com/mozilla/webextension-polyfill#api-methods-or-options-that-are-only-available-when-running-in-firefox

**Comment by yuzd** [comment]
nice job
