### ISSUE TITLE
Support promise-based API for `browser.tabs.goBack` and `browser.tabs.goForward`

### ISSUE THREAD

**Issue by infokiller** [mozilla/webextension-polyfill#243]
Seems they are [supported by Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/goForward), but they're not in https://github.com/mozilla/webextension-polyfill/blob/master/api-metadata.json

**Comment by Rob--W** [comment]
It was added in https://bugzilla.mozilla.org/show_bug.cgi?id=1603796.

We should indeed add those to the polyfill.

**Comment by Rob--W** [comment]
To resolve this, add the definitions for `goBack` and `goForward` to https://github.com/mozilla/webextension-polyfill/blob/01fb67f0475473fbedea061323a9fc030ee2094c/api-metadata.json#L520

**Comment by infokiller** [comment]
Thanks @Rob--W , is that the only required change?

**Comment by Rob--W** [comment]
Yes.

**Comment by ariain** [comment]
@Rob--W can I work on this issue??

**Comment by infokiller** [comment]
@ariain I already submitted a PR

**Comment by ariain** [comment]
okay @infokiller ....
