### ISSUE TITLE
identity.launchWebAuthFlow with interactive: true doesn't return the token on Firefox

### ISSUE THREAD

**Issue by PedroS11** [mozilla/webextension-polyfill#248]
Hi, I'm developing a chrome/firefox extension using this package and when it opens, I need to get an oauth2 token. 
The following snippet works on Chrome but in Firefox
```

const browser = require("webextension-polyfill");
...
const redirectURL = await browser.identity.launchWebAuthFlow({
            url: <request URL>,
            interactive: true,
        });

```
with this, it opens a new tab with the login page to authorize and it sends the token as a query parameter that should be stored on "redirectUrl". The problem is, it doesn't return anything, the code crashes there and doesn't go through. I wrapped it around a try/catch and nothing is logged and I can't retrieve the token. If I set interactive: false is works like a charm. Does anybody have an idea what's happening? It's just firefox, with chrome interactive true or false works both ways.

Update:
Apparently, this is due to mozila when the auth page opens, it closes the extension and you can't send the token to the extension (https://stackoverflow.com/questions/63746677/launchwebflow-in-firefox-extension-closes-the-extension-window-on-oauth2-popup) Did anyone have this problem?

PS: I'm trying to get an oauth2 token from Twitch API.

**Comment by Rob--W** [comment]
This is not an issue with the polyfill. On Firefox, the polyfill is a no-op.

Do you have a minimal test extension to demonstrate the issue?
If I see that I may be able to explain why your code is not working.
If there is a bug in Firefox I would also be interested in getting it fixed.

**Comment by rpl** [comment]
@PedroS11 based on the "Update: ..." part of the issue description I'm guessing that the identity.launchWebAuthFlow is originated from a browserAction or pageAction popup, those popups are going to be autoclosed as soon as they lose focus, which would explain why the caller can't successully get a result (given that the entire extension popup window global has been already destroyed).

To workaround this issue in Firefox the identity.launchWebAuthFlow has to be called from a page that isn't going to be destroyed when it does lose focus (e.g. from the background page if the oauth flow has to absolutely be started from a browserAction/pageAction popup, or it may be originated from a sidebar page or a popup window created using the `browser.windows.create` API method).

I'm closing this as invalid from a polyfill perspective, as Rob did already mention on Firefox the polyfill is a no-op.
