### ISSUE TITLE
Errors aren't instances of Error

### ISSUE THREAD

**Issue by fregante** [mozilla/webextension-polyfill#257]
Run this in background.js:

```js
browser.permissions.request({origins:["<all_urls>"]})
	.catch(err => console.log(err instanceof Error, err))
```

Firefox:

<img width="741" alt="true" src="https://user-images.githubusercontent.com/1402241/105568764-81dc9700-5d01-11eb-9b2d-9cd19382040e.png">

Chrome:

<img width="732" alt="false" src="https://user-images.githubusercontent.com/1402241/105568759-74271180-5d01-11eb-98a6-46ee9999ddbf.png">

Source:

https://github.com/mozilla/webextension-polyfill/blob/716c90bca4c8c83aa9b9615e1ecd2b8f1e69d512/src/browser-polyfill.js#L97-L98

Suggested code:

```js
        if (extensionAPIs.runtime.lastError) {
          promise.reject(new Error(extensionAPIs.runtime.lastError.message));
```

**Comment by Rob--W** [comment]
Why would you want an Error instance here? It would be rather meaningless (stack, type doesn't add value).

**Comment by fregante** [comment]
Specifically i found out about this because I was using `alert(error)`, which printed a nice 'Error: blah blah' in Firefox but '[object Object]' in Chrome. Additionally I was under the impression that polyfills are meant to standardize a set of APIs, so if something works on Firefox it should work the same in Chrome too, unless impossible (like the stack part)

**Comment by fregante** [comment]
I noticed an instance (heh) where a real Error is thrown https://github.com/mozilla/webextension-polyfill/blob/5f7a8458c9b249052816f520e4f8b13bf6337000/src/browser-polyfill.js#L457
