### ISSUE TITLE
Export as module

### ISSUE THREAD

**Issue by collinsauve** [mozilla/webextension-polyfill#29]
I would like to use this as a module in webpack.   Would it be possible to publish a version that exports `browser`?

I made an attempt on this PR and it did work when I consume it as a module, however the way the tests load the script don't work: https://github.com/mozilla/webextension-polyfill/pull/28

**Comment by collinsauve** [comment]
Refactored the way I do the export here: https://github.com/mozilla/webextension-polyfill/pull/31

**Comment by rpl** [comment]
Fixed by #17
