### ISSUE TITLE
Support for chrome

### ISSUE THREAD

**Issue by kiran-collab** [mozilla/webextension-polyfill#297]
Respected all!
I have a custom firefox plugin, made for firefox browser. I wish to run it on chrome.
I have downloaded "browser-polyfill.js" and referenced it in manifest and other html files. 
However the plugin doesn't behave as expected in chrome. 
What else would I have to do so it may run properly in chrome.
I would be grateful if anyone can address the above at the earliest!
Thankyou!

**Comment by Rob--W** [comment]
Could you share the source code or a link to the repository that holds the source code? Without it there is not much help to offer here.

**Comment by kiran-collab** [comment]
@Rob--W Respected Sir
I am sharing the link to the repo to source code..
Link: https://github.com/kiran-collab/browser-plugin
I would be grateful if you could guide!

**Comment by Rob--W** [comment]
Your extension isn't using any module loader, yet you're using `require`. Remove that line and it should work: https://github.com/kiran-collab/browser-plugin/blob/7c91391c2b52d93e16bc8e161a4f6cb9429df31b/background.js#L1

See https://github.com/mozilla/webextension-polyfill#basic-setup

**Comment by kiran-collab** [comment]
@Rob--W 
Hi Sir
I have removed  the 'require' line. 
However the plugin does not work as expected i.e. blur obscene images in chrome.
I would be grateful if you could kindly give the necessary changes, as I am completely new to this.
I am open to a online session as well for your guidance.

I have added all the files in the repo. 
Maybe you may try at your end and check. 
Thankyou!

**Comment by Rob--W** [comment]
I'm sorry, but I don't have time to look into a project that's completely unrelated to anything I'm working on. I suggest to use your development and debugging skills to resolve your tasks.
