### ISSUE TITLE
`runtime.onMessage.addListener` with a Promise does not work in Chrome

### ISSUE THREAD

**Issue by martonlederer** [mozilla/webextension-polyfill#301]
I followed the example in the Mozilla Webextension docs ([here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage#sending_an_asynchronous_response_using_a_promise)) and it does not seem to work in Chromium based Brave browser.

I get a response from the background script right away, but it is `null`, no matter what i return. If the listener is synchronous, it works just fine.

Any tips, or is this a known issue?

**Comment by rpl** [comment]
@martonlederer we do have an integration test that should cover the same behavior from the example you linked (the intergration test is this one: [test/fixtures/runtime-messaging-extension](https://github.com/mozilla/webextension-polyfill/tree/master/test/fixtures/runtime-messaging-extension)), that test runs on every change and so it should be working.

You'll need to provide a minimal test extension and some more details (e.g. what is the expected vs. actual behavior) to allow us to double-check if it is an issue with how the API or the polyfill is being used, or if it is a legit (and maybe known) issue.

**Comment by martonlederer** [comment]
Yes sorry @rpl, so here is a basic example that does not work:

`content_script.js`:
```
browser.runtime.sendMessage("test")
  .then((res) => console.log(res))
```

`background_script.js`:
```
browser.runtime.onMessage.addListener(async (msg) => {
  console.log(msg);
  await axios.get("https://google.com").then(() => console.log("done"))
  return {test: "hi"}
})
```
The message arrives to the background script, but the response returned to the content script is simply `null`

**Comment by martonlederer** [comment]
Now I'm wondering if this is because for my usecase (for multiple asynchronous function) I should use a long lived [connection](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/connect)

**Comment by martonlederer** [comment]
Yep the above solution helped. Although I'm not sure why was this a problem, my promise does not take a long time to resolve

**Comment by rosswintle** [comment]
Huh. I have EXACTLY this issue, with a similar minimal case to replicate, and I'm SO frustrated.

Did the polyfill maintainers ever look into it?

My stripped-down code is:

### content script

```
        // Check the request cache
        const requestCache = await browser.runtime.sendMessage({
            action: 'fetchData',
            key: 'wpe-installs-cache'
        });

        console.log('requestCache', requestCache);
```

### background script

```
browser.runtime.onMessage.addListener((data, sender) => {
    if (data?.action !== 'fetchData') {
        return;
    }

    return browser.storage.local.get([data.key]).then((result) => {
        console.log(result);
        return({foo: 'bar'});
    });
});
```

Yes, I've switched my async/await and promise is the other way around, but trust me, I've tried this EVERY possible way, and the console.log always shows `requestCache null`.

My example also matches the format of one of the [examples in the README](https://github.com/mozilla/webextension-polyfill#examples), but with the content script and background script switched.

Am I doing something wrong here? Seems to be the same issue.

**Comment by Rob--W** [comment]
> Huh. I have EXACTLY this issue, with a similar minimal case to replicate, and I'm SO frustrated.
> 
> Did the polyfill maintainers ever look into it?
>
> ...
> Yes, I've switched my async/await and promise is the other way around, but trust me, I've tried this EVERY possible way, and the console.log always shows `requestCache null`.

Works for me, I tried a range of Chrome versions from 100 to 113 and it works as expected. Upon loading the extension and visiting example.com, the expected message is logged in the console (i.e. the storage result).

Directory:
- manifest.json
- background.js (same as [above comment](https://github.com/mozilla/webextension-polyfill/issues/301#issuecomment-1440783426))
- contentscript.js (same as [above comment](https://github.com/mozilla/webextension-polyfill/issues/301#issuecomment-1440783426), wrapped in async IIFE)
- browser-polyfill.js from https://unpkg.com/webextension-polyfill@0.10.0/dist/browser-polyfill.js

### manifest.json:

```json
{
    "name": "webextension-polyfill + messaging example",
    "description": "Load the extension and visit example.com, then look at the console to see if requestCache is not null",
    "version": "1",
    "manifest_version": 2,
    "background": {
        "scripts": ["browser-polyfill.js", "background.js"],
        "persistent": true
    },
    "content_scripts": [{
        "run_at": "document_idle",
        "js": ["browser-polyfill.js", "contentscript.js"],
        "matches": ["*://*.example.com/*"]
    }],
    "permissions": ["storage"]
}
```

### background.js
```js
browser.runtime.onMessage.addListener((data, sender) => {
    if (data?.action !== 'fetchData') {
        return;
    }

    return browser.storage.local.get([data.key]).then((result) => {
        console.log(result);
        return({foo: 'bar'});
    });
});
```

### contentscript.js
```js
(async () => {
        // Check the request cache
        const requestCache = await browser.runtime.sendMessage({
            action: 'fetchData',
            key: 'wpe-installs-cache'
        });

        console.log('requestCache', requestCache);
})();
```
