### ISSUE TITLE
chrome.tabCapture.capture implementation not found

### ISSUE THREAD

**Issue by snorreks** [mozilla/webextension-polyfill#303]
I have not found found an equivalent of using chrome.tabCapture.capture, is there another way to screen record the current tab?

**Comment by Rob--W** [comment]
The `tabCapture` API is only supported by Chrome, so it is not part of the polyfill according to https://github.com/mozilla/webextension-polyfill#no-promise-returned-on-chrome-for-some-api-methods

In case you're wondering about screen capturing in Firefox: you don't need an extension for that, see https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API
