### ISSUE TITLE
runtime.sendMessage doesn't pass callback to onMessage listeners

### ISSUE THREAD

**Issue by kmarple1** [mozilla/webextension-polyfill#307]
I'm attempting to test my onMessage listeners, but I keep getting the error `TypeError: sendResponse is not a function`. It appears that the implementation of runtime.sendMessage *accepts* a callback as the second argument, but doesn't actually pass it to the listener.

My workaround thus far has been to pass a default value to my listeners, ex:
```browser.runtime.onMessage.addListener((request, sender, sendResponse = () => {}) => {```

While this gets rid of the error, not being able to check the results passed to the callback make the test almost useless.

**Comment by Rob--W** [comment]
How are you testing this?

The current version of the polyfill passes the `sendResponse` listener at https://github.com/mozilla/webextension-polyfill/blob/50be150c25e039c5aa6f9715b7c50135f4204324/src/browser-polyfill.js#L422 This behavior was introduced in [version 0.3.0](https://github.com/mozilla/webextension-polyfill/releases/tag/0.3.0) and is still present in the [latest version](https://github.com/mozilla/webextension-polyfill/releases) (0.8.0). Are you using the latest version of the polyfill?

**Comment by kmarple1** [comment]
OK, I actually posted this in the wrong repo; I meant to post it to `clarkbw/jest-webextension-mock`. If I try to use the polyfill directly from jest, I always get the error `This script should only be loaded in a browser extension.`

**Comment by Rob--W** [comment]
Closing since this is bug report is unrelated to this project and a bug report has been filed at https://github.com/clarkbw/jest-webextension-mock/issues/136

**Comment by escapedcat** [comment]
Just for others ending up here, this helped me: https://github.com/mozilla/webextension-polyfill/issues/218#issuecomment-584894114
