### ISSUE TITLE
Add the sendResponse parameter in onMessage Listener

### ISSUE THREAD

**Issue by WebExp0528** [mozilla/webextension-polyfill#311]
Please add the sendResponse parameter in onMessage Listener.
![image](https://user-images.githubusercontent.com/46267354/117150278-d82f8c00-ad6c-11eb-89cb-44ef244f7956.png)
![image](https://user-images.githubusercontent.com/46267354/117150373-f1383d00-ad6c-11eb-8da3-c472d94d0469.png)

**Comment by Rob--W** [comment]
This report is misplaced. The issue that you're reporting is not related to this repository. It seems that you're reporting a bug in the `webextension-polyfill-ts` project, but this is the `webextension-polyfill` repository.

It also appears that your issue has been reported before at https://github.com/Lusito/webextension-polyfill-ts/issues/54

**Comment by WebExp0528** [comment]
Aha. Thank you.
