### ISSUE TITLE
Error when running a script on an external webpage

### ISSUE THREAD

**Issue by FUZIK** [mozilla/webextension-polyfill#316]
An error occurs when I add a script with `<script>`
There is an error in the script when importing 'webextension-polyfill'
Error: **This script should only be loaded in a browser extension.**

_webpage-inject.js_
```
function sendHello(): void {
  const extensionPort = browser.runtime.connect(extensionId);
  extensionPort.postMessage('Hello, world!');
}
sendHello();
```

Code that throws an error. In my case, `!chrome.runtime.id` is `true`
https://github.com/mozilla/webextension-polyfill/blob/5ab825b83fd6f5c5f0643aa816880f8a41a41d2d/src/browser-polyfill.js#L543

**Comment by Rob--W** [comment]
The polyfill does not serve any purpose in a regular web page, as it is only useful in an extension. Why are you trying to load it in an external web page?

**Comment by FUZIK** [comment]
> 
> 
> The polyfill does not serve any purpose in a regular web page, as it is only useful in an extension. Why are you trying to load it in an external web page?

I add a script to the page for access the context of the page.
I also have a `onConnectExternal` handler in the background scripts.
This way I create a bridge between the page and the extension. I use this method because content scripts work in their own context.
Read more: https://developer.chrome.com/docs/extensions/mv3/content_scripts/#isolated_world
