### ISSUE TITLE
Publish to npm for use with browserify/webpack/etc.

### ISSUE THREAD

**Issue by BigBlueHat** [mozilla/webextension-polyfill#32]
For new WebExtension developers its a bit tedious to download, install dependencies, grunt, and then copy out the built JS file. It would be nicer to `npm i --save-dev` or something.

Alternatively, hosting a built copy here in releases--even if marked pre-release--would make using this much easier for newcomers.

Thanks!
🎩

**Comment by rpl** [comment]
Hi @BigBlueHat, thanks for reporting this, I totally agree with you!

This should now be fixed (by #17, #35, #36 and #37).

- https://www.npmjs.com/package/webextension-polyfill
- https://github.com/mozilla/webextension-polyfill/releases/tag/0.1.1
