### ISSUE TITLE
Usage on `externally_connectable` websites is not supported

### ISSUE THREAD

**Issue by fregante** [mozilla/webextension-polyfill#326]
I don't know what's your stance on `externally_connectable` since it's not yet supported in Firefox but in short it makes the `chrome.runtime.sendMessage` API available outside extensions.

Unfortunately there's this snippet of code that's blocking the execution of the polyfill in this context, even though the `chrome` API exists and works.

https://github.com/mozilla/webextension-polyfill/blob/4b2afe89fd64bd2357511a98593ccc4628d58b47/src/browser-polyfill.js#L543-L545

Everything is truthy except the last `chrome.runtime.id`, which is undefined.

**Comment by Rob--W** [comment]
This is intentional.

The polyfill is designed for use in an extension context. `externally_connectable` is only supported in Chrome and rarely used. Checking for errors and returning early allows library consumers to detect early when they are running a polyfill in an environment for which it is not designed. For a bit more context, see https://github.com/mozilla/webextension-polyfill/issues/316#issuecomment-835841963

**Comment by fregante** [comment]
I disagree with the context part. If a compatible `chrome` API exist I see no reason not to support it. There’s nothing special about the extension context other than the API itself. 

Now if this is a polyfill specifically for Firefox then, sure, but the name suggests otherwise.

In the end this is possibly an extremely minor change required that would allow usage in a context that Chrome supports and Firefox has an open issue to support.

Can you change the check from .id to .sendMessage? Or add it as an alternative?

**Comment by Rob--W** [comment]
I'll re-open for discussion at the next bug triage.

**Comment by rpl** [comment]
We discussed about this issue during our last triage meeting and we have agreed that we still consider this request outside the scope of the polyfill and agreed to close it as wontfix.

Follows some notes related to the rationale behind our decision:

- Besides the fact that the website or the extension developers would still need to execute the polyfill in the context of the webpage that would need to use it (which is most cases it may be a specific website or a specific group of websites), even including the polyfill wouldn't still be enough to make the extension able to work on both Chrome and Firefox without further "polyfilling" the missing pieces (the fact that the `chrome` / `browser` API object would not be available as it would on Chrome).

- The extension APIs actually exposed to the webpages in chrome are a very small subset, basically a couple of API methods and a couple of API events related to the extensions messaging APIs, and each website / extension would likely use only one of them (the message based API or the port based API), and so in practice the website / extension developers would very likely just need to promisify a single API method, which would be easy enough to achieve without having to run in the webpage this entire polyfill (and they can decide to do so independently from what API-style, promise or callback based, the extension is using internally).
