### ISSUE TITLE
Usage _without_ Modules

### ISSUE THREAD

**Issue by fosskers** [mozilla/webextension-polyfill#328]
I am in what seems like a rare scenario: I am (successfully!) building Web Extensions that run WASM, compiled from Rust. These extensions are also capable of arbitrary amounts of multithreading, but a consequence of that setup is that JS modules are in no way allowed.

Everything has gone perfectly in Firefox thusfar, but an attempt to add Chrome support via `browser-polyfill.js` isn't going well. I'm referencing the file in `index.html` in the usual way:
```html
    <script type="application/javascript" src="browser-polyfill.js"></script>
```
but upon loading this file, Chrome tells me:

> Uncaught ReferenceError: module is not defined
 
citing the line:
```js
  // The build process adds a UMD wrapper around this file, which makes the
  // `module` variable available.
module.exports = wrapAPIs(chrome);
```
Given that I'm not using a bundler of any sort, and thus there is no "build process" to speak of, I guess `module` never exists as a symbol. 

Can this polyfill be used _without_ assuming the `module` symbol is in scope? Can I inject the `browser` symbol into the global namespace in some other way?

**Comment by Rob--W** [comment]
Could you show a test case that reproduces the issue? `module` in the polyfill script is a local variable. Based on feature detection, the right export target is chosen. The logic is here: 
https://github.com/mozilla/webextension-polyfill/blob/4b2afe89fd64bd2357511a98593ccc4628d58b47/scripts/babel-transform-to-umd-module.js#L3-L21

The error that you've got could happen if you've defined an `exports` global variable.

**Comment by fosskers** [comment]
The `module` symbol is only referenced at the very end of `browser-polyfill.js`. The code you've cited here is in a different script entirely which is never called in my scenario. I'll reiterate that the usual JS tools (webpack, etc.) aren't in use here at all. `browser-polyfill.js` is just being linked to from the HTML as-is.

The following HTML reproduces the issue:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <script type="application/javascript" src="browser-polyfill.js"></script>
  </head>
  <body></body>
</html>
```

**Comment by fosskers** [comment]
Wait a minute... the version from the `.zip` file I downloaded is ~800 lines shorter than the one available on unpkg. Perhaps I downloaded the raw, unprocessed source code and was trying to use that? 

Let me try the unpkg version.

**Comment by fosskers** [comment]
Now that I've done that, the error seems to be gone. I will recheck my actual JS bindings now and see if it all works as expected.

**Comment by fosskers** [comment]
Yup, it all works now. Thank you!
