### ISSUE TITLE
Build Fail when creating extension with Next.js

### ISSUE THREAD

**Issue by zluo01** [mozilla/webextension-polyfill#346]
I am currently trying to develop an extension by using Next.js to create static html pages.

However, when I try to build my package I encounter error `Error: This script should only be loaded in a browser extension.` which comes from the following code
```
  if (typeof chrome != "object" || !chrome || !chrome.runtime || !chrome.runtime.id) {
    throw new Error("This script should only be loaded in a browser extension.");
  }
```

I am curious what this condition tries to check and how it can affect code in build time ? 

Thank you.

**Comment by Rob--W** [comment]
This condition checks that the code is running in an extension environment. The polyfill provides functionality for extension code, it doesn't make sense to run it in a web page. See also the thread at https://github.com/mozilla/webextension-polyfill/issues/316
