### ISSUE TITLE
Unexpected property: 'allowScriptsToClose' while windows.create in Chrome

### ISSUE THREAD

**Issue by ANovitsky** [mozilla/webextension-polyfill#347]
` windows
        .create({
          url: url,
          type: 'popup',
          height: 600,
          width: 600,
          top: y,
          left: x,
          allowScriptsToClose: true
        })
        .then((win: any) => {
          resolve(win);
        })
        .catch((e: any) => {
          reject(e);
        });`
I got error in Chrome Version 95.0.4638

### "Error in invocation of windows.create(optional object createData, optional function callback): Error at parameter 'createData': Unexpected property: 'allowScriptsToClose'."

I thinking because the method doesnt have it [https://developer.chrome.com/docs/extensions/reference/windows/#method-create](https://developer.chrome.com/docs/extensions/reference/windows/#method-create)

**Comment by ANovitsky** [comment]
But it have in FireFox [https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create)

**Comment by rpl** [comment]
Polyfilling features that are missing in Chrome is explicitly stated as out of scope for the library: https://github.com/mozilla/webextension-polyfill#api-methods-or-options-that-are-only-available-when-running-in-firefox:

>   ##API methods or options that are only available when running in Firefox
>
>   This library does not provide any polyfill for API methods and options that are only available on Firefox, and they are actually considered out of the scope of this library.

In cases like this (when the extension may be passing options only available in a particular implementation of the WebExtensions APIs) the extension may have to detect on which browser is running and adjust the options to pass to the API method accordingly.

**Comment by Rob--W** [comment]
I believe that Chrome supports `window.close()` from extension code even without this option, at least that was the case a few years ago.
