### ISSUE TITLE
Polyfills polyfill globals

### ISSUE THREAD

**Issue by fregante** [mozilla/webextension-polyfill#350]
This polyfill is not acting as a polyfill, but rather as a regular module when used via bundlers. 

```js
import 'webextension-polyfill';
```

Polyfills are supposed to enable the API they're polyfilling; In this case, `globalThis.browser` is not available after bundling the above piece of code. That's unexpected for a polyfill. You would never `import {trimLeft} from 'string.prototype.trim-polyfill` (outside of testing environments), but rather `import 'string.prototype.trim-polyfill'`

## Possible solutions

- breaking: set `globalThis.browser` if it doesn't already exist, no UMD all 
- kinda-breaking: set `globalThis.browser` if it doesn't already exist AND set `module.exports`
- non-breaking: include 2 files:
	- the current UMD bundle (`import browser from 'webextension-polyfill'`)
	- a global-only bundle (`import 'webextension-polyfill/register'`)

or:

- meet me half way and into the future:
	- global-only bundle, for everyone even outside npm (`import 'webextension-polyfill'`)
	- ES module with `import browser from 'webextension-polyfill/module'`

## Side notes about UMD

- AMD is dead
- CommonJS is the de-facto standard, but if you really wanted to you could start distributing proper a ES module its place (on its own this would not resolve this issue though)

## Context

- https://github.com/mozilla/webextension-polyfill/issues/231
- https://github.com/mozilla/webextension-polyfill/issues/169
- https://github.com/mozilla/webextension-polyfill/issues/100
- https://github.com/mozilla/webextension-polyfill/issues/73

**Comment by Rob--W** [comment]
> set `globalThis.browser` if it doesn't already exist, no UMD all

Note that `globalThis.browser` could also be set if the page has an element with `id="browser"`. That's why the current check in the polyfill looks so complicated. "if it doesn't already exist" should not be a falsey check, but at least match the condition at https://github.com/mozilla/webextension-polyfill/blob/5dbb8d94b562cc05b1c87983ba066f37c829cacc/src/browser-polyfill.js#L9. For context see https://github.com/mozilla/webextension-polyfill/pull/153

**Comment by fregante** [comment]
> Note that `globalThis.browser` could also be set if the page has an element with `id="browser"`. That's why the current check in the polyfill looks so complicated. "if it doesn't already exist" should not be a falsey check, but at least match the condition at

That was a simplification, I'm just talking about dropping UMD, not the polyfill detection part.
