### ISSUE TITLE
how come i cannot access local??

### ISSUE THREAD

**Issue by 756445638** [mozilla/webextension-polyfill#362]
![image](https://user-images.githubusercontent.com/12948870/153536085-efbf649a-9602-4502-95cd-cbcc5a2d03ef.png)

**Comment by Rob--W** [comment]
There aren't enough details in this report to answer your question, but the most likely answer is that your extension is missing the "storage" permission in the manifest.json file.

**Comment by 756445638** [comment]
ok. I will try later. thanks.
