### ISSUE TITLE
No-op mode doesn't work on Safari

### ISSUE THREAD

**Issue by Helloyunho** [mozilla/webextension-polyfill#364]
In Safari, no-op mode doesn't work as the line below returns true.

https://github.com/mozilla/webextension-polyfill/blob/f818ecbac3c0a4b67998014a16898210cf80e715/src/browser-polyfill.js#L13

Strangely, the browser object on Safari inherits `CallbackObject`. So `Object.getPrototypeOf(globalThis.browser)` doesn't return `Object`.

`Object.getPrototypeOf(Object.getPrototypeOf(globalThis.browser)) !== Object.prototype` finally gives the expected value.

![CleanShot 2022-03-02 at 23 14 30](https://user-images.githubusercontent.com/10192625/156378608-8b6716d6-e20b-4341-888d-4d04a1c4e050.png)

**Comment by Helloyunho** [comment]
It's almost the end of the year and I still couldn't find a solution for this 😢

**Comment by xeenon** [comment]
This can now be closed.

**Comment by Helloyunho** [comment]
> This can now be closed.

Yeah, seems like https://github.com/mozilla/webextension-polyfill/pull/582 fixes this issue
I can't test right now but I believe the PR so Imma close the issue
