### ISSUE TITLE
Type error when calling Storage API in Chrome

### ISSUE THREAD

**Issue by momo3038** [mozilla/webextension-polyfill#366]
Hello,

I'm quite happy with the WebExt polyfill but I encountered an issue today with Chome (99.0.48 and also 100.X) and the storage API. I'm not able to work with the "get" function in Chrome and I receive the following error: 

`Uncaught (in promise) TypeError: Error in invocation of storage.get(optional [string|array|object] keys, function callback): No matching signature.`

Everything is working fine in Firefox (storage get, storage set, ..) when I run such code:

`await browser.storage.sync.get(null);`

But not in Chromium (Edge, Chrome, ...).

With the chome api, it works as expected ...

`      chrome.storage.local.get(['key'], function(result) {
        console.log('Value currently is ' + result.key);
      });`

 Is the polyfill broken because of a new Chrome update ?

Thanks !

**Comment by momo3038** [comment]
It was a bundler issue. Sorry for that issue.

**Comment by reccanti** [comment]
@momo3038 Do you know what the specific issue was or how you fixed it? Running into a similar issue with `tabs.sendMessage` right now 😅

**Comment by momo3038** [comment]
I don't know why but I had to change the way I do the polyfill import. Then my bundler (esbuild) correctly bundle the polyfill. Hope this help.

https://github.com/momo3038/another-pomodoro-webextension/blob/master/src/background.ts#L1
