### ISSUE TITLE
browser.permissions.request doesn't return a promise

### ISSUE THREAD

**Issue by olsh** [mozilla/webextension-polyfill#38]
Browser: Chrome 58
Library version: 0.1.1

I'm using this code on an extension options page:

```js
browser.permissions.request({
            origins: ["<all_urls>"]
        }).then(function (granted) {
                // do something
            })
```

The popup request is showing, but the code throws the error:

```
Uncaught TypeError: Cannot read property 'then' of undefined
```

**Comment by shatgupt** [comment]
Encountered this issue while trying to use optional permissions.

**Comment by romantaraban** [comment]
The library is missing definitions for permissions APi in api-metadata.json, please see #44

**Comment by sladiri** [comment]
Could you please explain how this issue is resolved? I cannot get this permissions example to work, since `browser.permissions.request({ permissions: ['history'] })` never resolves.
`Firefox 67.0b16 (64-bit)`

https://github.com/mdn/webextensions-examples/blob/master/permissions/page.js

**Comment by sladiri** [comment]
I was unaware that this API is new and seems to be not really consistent yet. So I guess I just have to wait, I agree with this answer on SO https://stackoverflow.com/a/47729896/7309920
