### ISSUE TITLE
MV3 scripting API doesn't seem to be available

### ISSUE THREAD

**Issue by Manvel** [mozilla/webextension-polyfill#382]
It seems like [MV3 scripting API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting) is not available yet. 

I am not sure what is the plan for `webextension-polyfill` to support MV3, but I am happy to try helping adding support for `scripting` API, if you say that you plan supporting MV3.

P.S. Also thanks to Mozilla team for helping devs to bring Web Extensions to more platforms with this amazing tool ❤️

**Comment by Rob--W** [comment]
The behavior of the polyfill with MV3 should be documented somewhere, but for now the answer can be found in my earlier comment at #329. The behavior of the polyfill is explained at https://github.com/mozilla/webextension-polyfill/issues/329#issuecomment-884938069.

The `scripting` API supports promises already, so the `scripting` API should be usable even without changes to the polyfill.

**Comment by Manvel** [comment]
Thanks for the reply @Rob--W 

> The scripting API supports promises already, so the scripting API should be usable even without changes to the polyfill.

Interesting, the last time I checked it wasn't available through `browser` namespace, but [only after scripting were added to api-metadata.json ](https://github.com/mozilla/webextension-polyfill/pull/383/files).

I will do tests again and provide minimized test case over the weekend. Probably I am missing smth. 🤔

**Comment by Manvel** [comment]
Yeah, I can confirm that `scripting` still works, not sure why previously I couldn't make it work, might be missing permission. Sorry for the noise, should have tested more attentively.
