### ISSUE TITLE
chrome.runtime.id is undefined if running in a conten script in world:MAIN

### ISSUE THREAD

**Issue by naugtur** [mozilla/webextension-polyfill#390]
Under manifest v3 there's limited ability to access the page's window from a content script. It can only be done if `world:'MAIN'` is set when adding the script and that only works since chrome 102.something

```js
chrome.scripting.registerContentScripts([
  {
    id: 'csmain',
    matches: ['file://*/*', 'http://*/*', 'https://*/*'],
    js: ['contentscript.js'],
    world: 'MAIN',
    runAt: 'document_start',
  }])
```

contentscript.js is bundled with browser-polyfill.js  
This check in the polyfill is failing:
```js
 if (typeof chrome != "object" || !chrome || !chrome.runtime || !chrome.runtime.id) {
      throw new Error("This script should only be loaded in a browser extension.");
    } 
```

I might be able to put together a minimal repro. Trying to ask Googlers first.

**Comment by naugtur** [comment]
When I disarm the throw, the next error I get is 
```
TypeError: _webextensionPolyfill.default.runtime.getURL is not a function
```

**Comment by Rob--W** [comment]
The main world does not have access to extension APIs. See #389 and #326 for more details.

**Comment by naugtur** [comment]
Ok, I got the hang of it. Thanks for the links.
