### ISSUE TITLE
I cant pass data from page to extension...

### ISSUE THREAD

**Issue by DenisLopatin** [mozilla/webextension-polyfill#410]
Hello. I have one task. I have to get the data from the page and send it to my extension number. Unfortunately, the following example does not work:

manifest.json

```
{
    "manifest_version": 3,
    "name": "Name",
    "version": "1.0",
    "description": "description",
    "icons": {
        "128": "128.png"
    },
    "action": {
        "default_popup": "index.html"
    },
    "content_scripts": [
        {
            "matches": ["<all_urls>"],
            "js": ["src/browser-polyfill.js", "index.js"],
            "css": ["index.css"],
            "run_at": "document_start"
        }
    ],
    "background": {
        "service_worker": "background.js"
    },
    "permissions": ["tabs", "storage", "webRequest", "<all_urls>", "scripting", "storage", "notifications"]
}
```

index.js

```
document.addEventListener('click', (event) => {
        console.log(event.target);

        browser.runtime.sendMessage({ name: 'Denis' }).then((response) => {
            console.log(response);
        });
});
```

background.js

```
browser.runtime.onMessageExternal.addListener(async (msg) => {
    console.log(msg);
    return Promise.resolve({response: "Hi from content script"});
})
```

What do I want? In index.js file I receive data and transfer it to background.js . On the background.js I processes this data. But when I click on the page - nothing happens.

**Comment by Rob--W** [comment]
Use runtime.onMessage, not runtime.onMessageExternal.

**Comment by DenisLopatin** [comment]
I used a lot of options, eventually managed to solve the problem. I described it on [stackoverflow ](https://stackoverflow.com/questions/73724519/i-cant-send-data-from-the-page-to-the-extension/73731897#73731897) and I don't want to repeat it. I hope this helps. Please note that I refused the polyfill
