### ISSUE TITLE
Background onMessage.addListener sender error tab.id allway be 1.

### ISSUE THREAD

**Issue by jason-chang** [mozilla/webextension-polyfill#416]
In background script when i try to reply message to sender tab allway got error like below.  

![image](https://user-images.githubusercontent.com/4367687/198236798-2fd10c03-2059-4dc7-a408-1c6429d43e95.png)

Because. `sender.tab.id` allways be `1`.

My code like below:
```typescript
browser.runtime.onMessage.addListener(async (body: MsgBody, sender) => {
  
    let tabId = sender.tab.id || 0;
    
    browser.tabs.sendMessage(tabId, {
      extensionId,
      type: 'DLQ_START_SUCCESS',
    );
})
```

**Comment by Rob--W** [comment]
Could you share the project that you're using to reproduce this issue?
