### ISSUE TITLE
Polyfill `browser.commands.update`?

### ISSUE THREAD

**Issue by vialoh** [mozilla/webextension-polyfill#417]
Apparently Firefox is currently the only browser that supports [`browser.commands.update`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands/update#browser_compatibility).

Would it make sense to add a polyfill for other browsers?

I can submit a PR when I have the time. I'd probably use something like [hotkeys.js](https://github.com/jaywcjlove/hotkeys), limit the key combinations to those listed [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#key_combinations), and use [storage.sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync) to load users' changes.

**Comment by Rob--W** [comment]
A polyfill for `commands.update` is out of scope, see https://github.com/mozilla/webextension-polyfill#api-methods-or-options-that-are-only-available-when-running-in-firefox

The approach you sketched is not even equivalent: The `commands` API registers shortcuts that can be invoked from the browser UI, whereas the approach that you're thinking of would only work whereever you're able to run code in content to register listeners. Moreover, the need for extra permissions (host permissions to run content scripts, `storage` permission to persist preferences) means that the polyfill would require considerable set up, and all ultimately for behavior that is not identical.

In Chrome you'd better open `chrome://extensions/shortcuts` and instruct the user to set the shortcut there. That is simpler and results in the equivalent behavior.
