### ISSUE TITLE
flowjs type annotations?

### ISSUE THREAD

**Issue by karlicoss** [mozilla/webextension-polyfill#421]
Hi, I'm using flow.js for typechecking and wondering if there is any appetite for adding Flow.JS type annotations to this project? Are there any existing efforts? Did a bit of searching on github, but didn't find anything :( 

The closest I know is this project, but it's only for `chrome.` API namespace: https://github.com/Shraymonks/flow-interfaces-chrome

**Comment by Rob--W** [comment]
We're not interested in Flow types in this repo. We have some references to (external) projects that provide TypeScript definitions at https://github.com/mozilla/webextension-polyfill#usage-with-typescript

@rpl may recall whether there have been past attempts to define Flow types.
