### ISSUE TITLE
No types for browser.runtime.OnInstalledReason enum

### ISSUE THREAD

**Issue by everdimension** [mozilla/webextension-polyfill#447]
There is this object:
```
chrome.runtime.OnInstalledReason
```
But there are no types for:
```
browser.runtime.OnInstalledReason
```

I'm not sure whether all browsers are supposed to provide this enum, but this seems like a bug.
Reference:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/OnInstalledReason

Thanks!

**Comment by everdimension** [comment]
Btw this is what actually logs for `browser.runtime.OnInstalledReason`
![image](https://user-images.githubusercontent.com/5347023/228640494-18adf280-f404-44ac-b22d-05482a47e62a.png)

**Comment by Rob--W** [comment]
The `browser` object from the polyfill provides the expected object with "supported" enum values from the browser it's running in through `browser.runtime.OnInstalledReason`.

What's the problem here?

**Comment by Rob--W** [comment]
Closing for the lack of response, together with the observation that the library offers the enums as expected.

**Comment by fregante** [comment]
Types are not offered by this project, you're using a third party, likely: https://github.com/Lusito/webextension-polyfill-ts
