### ISSUE TITLE
Release should contain final built versions

### ISSUE THREAD

**Issue by soapdog** [mozilla/webextension-polyfill#47]
Hi,

The releases tab here in Github should contain the built versions of the polyfill including the final compressed version. The way it is now, it forces all users to download and build their own version which is basically equal to everyone else version.

Cheers

**Comment by shanemcgraw** [comment]
What's more, according to #41, a fresh build results in an eslint error 🙁

**Comment by rpl** [comment]
There is no need to rebuild locally, the dist files for the released versions of the npm package can be retrieved from unpkg, e.g.:

- https://unpkg.com/webextension-polyfill@0.1.2/dist/

but I agree, we should add a direct link which points to the dist directory on unpkg for every release description to make it easier to reach them (and I edited the release descriptions to include this link).

**Comment by Rob--W** [comment]
The documentation now explains more clearly how to get the release files: https://github.com/mozilla/webextension-polyfill#installation
