### ISSUE TITLE
Schoology API Key

### ISSUE THREAD

**Issue by peacefulporcupine** [mozilla/webextension-polyfill#475]
When I try to enable what-if grades, I get a message that says a Schoology API Key is required but has been blocked by my school or district. Is there any way to bypass or obtain an API Key so I can use What-If grades and other features?

![schoologysupport](https://github.com/mozilla/webextension-polyfill/assets/133718687/ea128ff7-3dc7-47b9-acfa-a00c8a4fff2d)

**Comment by Rob--W** [comment]
This is not the right location for these questions. We don't have anything to do with what you are asking about.
