### ISSUE TITLE
Error outside of promise with button notification

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [mozilla/webextension-polyfill#49]
```js
browser.notifications.create(notification_id, options)
	.catch(error=>{
		reject(error);
	})
;
```
I use a catch method to detect if the plateform support the buttons on notification (Firefox/Opera does not support them yet).
There's one problem with browser.notifications.create. In Firefox, this function use a Promise that should send the errors that the buttons are not supported in the catch of the Promise, and that's not the case.

**Comment by rpl** [comment]
That's unfortunate, but this polyfill is not applied when the extension is running on Firefox and so it cannot fix this kind of incompatibilities.

On the bright side, if you use it in an async function, there is no need to handle it differently for Firefox:

```js
  try {
    await browser.notifications.create(notification_id, optionsWithButtons);
    // supported
  } catch (e) {
    console.warn("Notification button not supported", e);
    // not supported (e.g. on Firefox, where the exception has been raised synchronously and Opera
    // where is will be raised as a rejection and turned into an exception by the await statement).
  }
```

In general Firefox raises an exception when the API method has been called with a parameter that is invalid (e.g. marked as unsupported) based on the JSON API schema (e.g. http://searchfox.org/mozilla-central/rev/f6dc0e40b51a37c34e1683865395e72e7fca592c/toolkit/components/extensions/schemas/notifications.json#86), and rejects the returned promise for the errors that cannot be verified by just validating the parameters based on the API schema (e.g. runtime errors, ids that are passed with the valid type but that do not exist anymore).
