### ISSUE TITLE
Can this plugin be used for message passing in Jupyter Lab plugins? 

### ISSUE THREAD

**Issue by blueluu** [mozilla/webextension-polyfill#494]
As the title suggests, if so, how can the following issues be resolved?
![image](https://github.com/mozilla/webextension-polyfill/assets/8735580/6e4ede29-5c9f-4b66-84fd-8b20bc10047c)

 Looking forward to your response.

**Comment by Rob--W** [comment]
This polyfill is for browser extensions. This is completely independent of the API supported by Jupyter: https://jupyterlab.readthedocs.io/en/latest/extension/extension_dev.html
