### ISSUE TITLE
Multiple inputs can not work

### ISSUE THREAD

**Issue by like-fly** [mozilla/webextension-polyfill#527]
In addition to popup.html, I have two other HTML files, namely src/login/login.html and src/selector/selector.html. While configuring them only in the additionalInputs of the WebExtension, I can access them using chrome.tabs.create({url: "src/login/login.html"}), but the hot reload feature doesn't work.

I found out that I can use the rollupOptions to configure multiple entry points. So, I configured it as follows:
```json
build: {
  rollupOptions: {
    input: {
      login: 'src/login/login.html',
      selector: 'src/selector/selector.html'
    }
  }
}
```
However, I encountered the following error: "Invalid value for option 'output.inlineDynamicImports' - multiple inputs are not supported when 'output.inlineDynamicImports' is true."

Therefore, I added the inlineDynamicImports configuration again:
```json
build: {
  rollupOptions: {
    input: {
      login: 'src/login/login.html',
      selector: 'src/selector/selector.html'
    },
    output: {
      inlineDynamicImports: false
    }
  }
}
```

How should I configure it so that the Vue pages referenced by login.html and selector.html can also have hot updates?

**Comment by Rob--W** [comment]
This does not look like an issue related to this project.
