### ISSUE TITLE
Nested runtime.sendMessage/tabs.sendMessage calls fail

### ISSUE THREAD

**Issue by adomasven** [mozilla/webextension-polyfill#53]
I've put together [this test case](https://github.com/adomasven/webextension-polyfill/tree/master/fail) real quick. This demonstrates how the `sendMessage` handler within `onMessage` handler is never triggered after the message being received from the initial `sendMessage` call from the content script.

I don't want to delve into the nastiness of where any of this gets swollen up within the chain of `Proxy`s and wrapper functions, but it's definitely not right.

To see the problem open the background tab and click the browser action icon. The expected order of logged lines is `okty plsRespond`, followed by `success`, but instead success is logged immediately and also a `"Could not establish connection. Receiving end does not exist."` error.

**Comment by Rob--W** [comment]
Works fine for me in Chromium 60.0.3112.90.

Chrome does not automatically run a content script in existing tabs when an extension is loaded.
Did you load a web page in the current tab before clicking on the extension button?

**Comment by adomasven** [comment]
Tested on Chrome 60.0.3112.101, Ubuntu 17.04 x64.

You need to open a web page (any page, but about: pages won't do) and then press the button and see the browser console.

**Comment by Rob--W** [comment]
By "works fine", I meant that I don't see an error message. The error message only shows up (as expected) when I click on the extension button in a tab that was loaded before the extension was loaded (or in a non-http(s) tab.

"success" is indeed printed before the "okty isResonse", but that's because you are directly calling `console.log` instead of putting it in a function. This works as expected:

```diff
diff --git a/fail/background.js b/fail/background.js
index 618f6f4..7741c61 100644
--- a/fail/background.js
+++ b/fail/background.js
@@ -1,5 +1,5 @@
 browser.browserAction.onClicked.addListener(function(tab) {
-    browser.tabs.sendMessage(tab.id, 'test').then(console.log('success'));
+    browser.tabs.sendMessage(tab.id, 'test').then(() => console.log('success'));
 });
 
 browser.runtime.onMessage.addListener(function(message, sender) {

```

**Comment by adomasven** [comment]
Ok, sorry to ripple the waters. This actually indeed works and I cannot replicate the issue I'm seeing in our larger codebase as a small test-case, so closing this for now.
