### ISSUE TITLE
Error in event handler: TypeError: browserPolyfillExports.tabs.executeScript is not a function

### ISSUE THREAD

**Issue by ishandutta2007** [mozilla/webextension-polyfill#542]
Typescript Code:

    import Browser from 'webextension-polyfill'
    Browser.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
        if (tab.url?.indexOf(HOME_URL) != -1 && changeInfo.status == 'complete') {
            console.log("will execute code on", tabId, changeInfo, tab);
            Browser.tabs.executeScript(tabId, {
                code: "alert('hi');"
            });
        }
    });

manifest.json

```
"manifest_version": 3,
"permissions": ["cookies", "tabs", "scripting"]
```

Error:
`
Error in event handler: TypeError: browserPolyfillExports.tabs.executeScript is not a function
`

Versions:

- webextension-polyfill: 0.10.0
- node v14.21.3

**Comment by Rob--W** [comment]
The tabs.executeScript is not supported in Manifest Version 3. Switch to scripting.executeScript instead.

**Comment by ishandutta2007** [comment]
@Rob--W Thanks

Pasting my updated working code for other's reference:

```
import Browser from 'webextension-polyfill'
Browser.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
    if (tab.url?.indexOf(HOME_URL) != -1 && changeInfo.status == 'complete') {
        console.log("will execute code on", tabId, changeInfo, tab);
        function myfunc() { alert('hi');} 
        Browser.scripting.executeScript(tabId, {
            target: {tabId: tabid, allFrames: true},
            func : myfunc
        });
    }
});

```
