### ISSUE TITLE
How not to include in Firefox

### ISSUE THREAD

**Issue by DamienCassou** [mozilla/webextension-polyfill#55]
My add-on sends webextension-polyfill dynamically to the active tab from a popup or sidebar. I would like to stop including the polyfill in Firefox releases of my add-on. How can I not send the polyfill in Firefox while still sending it to Chromium?

**Comment by Rob--W** [comment]
The polyfill is already guarded on `if (typeof browser === "undefined") {`, so it does not polyfill anything in Firefox:

https://github.com/mozilla/webextension-polyfill/blob/ab01b9605b94a1acdb7389b871d2edd749f7eb2f/src/browser-polyfill.js#L9

If you don't want to load the file at all, you can either modify you build script to not include the polyfill or use an empty file instead of the polyfill, or use `typeof browser === "undefined"` to detect at runtime whether you need the polyfill.

**Comment by DamienCassou** [comment]
thank you for your quick answer.

> it does not polyfill anything in Firefox

yes, I have been including the polyfill unconditionally for some time without trouble in [another add-on](https://gitlab.petton.fr/passwe/passwe-addon). Still, it bothers me to include code I don't need. Additionally, I get a lint warning when I do it:

```
Code            Message                     Description                                                                  File                      Line   Column
KNOWN_LIBRARY   Known JS library detected   JavaScript libraries are discouraged for simple add-ons, but are generally   browser-polyfill.min.js                
                                            accepted.                                                                                                           
```

Nothing serious here. It would just be nicer not to include it.

> you can either modify you build script to not include the polyfill 

if I do that, how do you suggest to adapt this code?

```javascript
async function sendScript (tabId) {
  await browser.tabs.executeScript(tabId, {file: '/browser-polyfill.min.js'})
  await browser.tabs.executeScript(tabId, {file: '/content-script.js'})
}
```

> use an empty file instead of the polyfill

that's a bit ugly, but the best solution I have heard so far. Thanks :-).

> use typeof browser === "undefined" to detect at runtime whether you need the polyfill

that's not going to work here as the code which sends the content-script already knows about `browser`.

**Comment by Rob--W** [comment]
You could save the result of `typeof browser === "undefined"` before you load the polyfill in the extension page that invokes `browser.tabs.executeScript`.

**Comment by asamuzaK** [comment]
Like this? (I did not test it though)
```
async function sendScript (tabId) {
  if (browser.runtime.id !== 'your_webext_id') {
    await browser.tabs.executeScript(tabId, {file: '/browser-polyfill.min.js'})
  }
  await browser.tabs.executeScript(tabId, {file: '/content-script.js'})
}
```

**Comment by DamienCassou** [comment]
@asamuzaK IIUC, you are proposing to distinguish the browser through the extension ID as it is going to differ from a browser to another one. This is smart. Thanks.

**Comment by bfred-it** [comment]
By the way, you don’t need to await `executeScript`, they’re executed in order anyway. I verified this before in chrome by having load a 70KB JS file first and then a one-liner.js: they still executed in order.

**Comment by Rob--W** [comment]
We have documented that the extension does not do anything in Firefox: https://github.com/mozilla/webextension-polyfill#issues-that-happen-only-when-running-on-firefox

If you somehow want to detect Firefox / Chrome based on API behavior, then the approach in https://github.com/mozilla/webextension-polyfill/issues/55#issuecomment-329676034 can be used (among others).
