### ISSUE TITLE
browser.devtools.* isn't polyfilled

### ISSUE THREAD

**Issue by marcysutton** [mozilla/webextension-polyfill#56]
First of all, thanks for writing and maintaining this polyfill! 

However...I'm trying to port a Chrome extension to Firefox and having a difficult time, as it seems that not all API methods are polyfilled. One example is [browser.devtools.panels.create](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/devtools.panels/create), which uses a callback signature in Chrome but is promise-based in Firefox. I've got the compiled polyfill implemented and Chrome is throwing an error:

```
Uncaught TypeError: Cannot read property 'then' of undefined
    at Object.2../actions/inspect (devtools.js:39)
    at s (devtools.js:1)
    at e (devtools.js:1)
    at devtools.js:1
```
That line points to this code:
```
browser.devtools.panels.create(name, '', 'panel/index.html').then((extensionPanel)  => {
//....
})
```
Is there a list of all the polyfilled methods somewhere, and/or perhaps a status for when the missing methods will be implemented? 

Edit: I see the metadata file does not include any devtools APIs. Bummer.

**Comment by rpl** [comment]
@marcysutton I'm going to look into this.

Unfortunately the devtools API namespace is the first nested namespace to be included in the polyfill, I've been testing this locally and it is currently not enough to just add the missing metadata in the api-metadata.json file (some changes to the browser-polyfill.js file are going to be required to handle the nested namespace correctly).
