### ISSUE TITLE
Support browser.sidePanel

### ISSUE THREAD

**Issue by abegehr** [mozilla/webextension-polyfill#583]
It seems that `chrome.sidePanel` is not supported as of now: https://developer.chrome.com/docs/extensions/reference/api/sidePanel - can/will it be?

I've ran into this trying to use `sidePanel` from WXT: https://github.com/wxt-dev/wxt/issues/570

**Comment by jlsalvador** [comment]
Currently, `browser.sidebarAction` is `undefined` in Chromium.

However, the following code works in Chromium:

```js
const [tab] = await chrome.tabs.query({
  active: true,
  lastFocusedWindow: true
});
chrome.sidePanel.open({
  windowId: tab.windowId
});
```
