### ISSUE TITLE
Uint8Array gets converted into object when using with sendMessage/onMessage

### ISSUE THREAD

**Issue by sharma66mahesh** [mozilla/webextension-polyfill#643]
I send an object with the following code from the UI side as follows:
```js
const result = await Browser.runtime.sendMessage({ action: 'GET_UINT8ARRAY' });
console.log(result)
```

Then I process this request on my background script and try to send back an uint8Array with the following code:
```js
Browser.runtime.onMessage((payload) => {
  if(payload.action == 'GET_UINT8ARRAY') {
    return new Promise(resolve => resolve({ uint8Arr: new Uint8Array([1,2,3]) }  ))
  } 
})
```

Expected result:
```js
{
  uint8Arr: [1, 2, 3]
}
```
Actual result received:
```js
{ 
  uint8Arr: {
    0: 1,
    1: 2,
    2: 3
  }
}
```

**Comment by Rob--W** [comment]
This is not an issue with the polyfill but with Chrome. Chrome has a serialization mechanism that does a bit more than JSON serialization, but is less capable than structured cloning.

Support for that is tracked at https://issues.chromium.org/issues/40321352
