### ISSUE TITLE
 webextension-polyfill ： Environment？

### ISSUE THREAD

**Issue by casey2024** [mozilla/webextension-polyfill#692]
Instead of loading the extension from the browser, run the extension directly in vscode and open the web page . There are always errors in chrome.runtime.id  from the webextension-polyfill  . For the development,  Is there a way to make the application run in vscode without loading from the chrome  browser   ???  Could you like to tell me?Thank you!

**Comment by Rob--W** [comment]
This polyfill is only usable in browser extension environments. The polyfill intentionally checks that it runs in such an environment because otherwise a later use of `browser` would trigger a runtime error anyway.

The polyfill does not provide implementations for missing functionality.
