### ISSUE TITLE
clipboardWrite in manifest.json produces error in Chrome with v0.2.1 of the polyfill

### ISSUE THREAD

**Issue by lidel** [mozilla/webextension-polyfill#70]
I have [a browser extension](https://github.com/ipfs/ipfs-companion) that requires `clipboardWrite` permission under Firefox.
(copying under Chrome works without any additional permissions)

Everything works fine with webextension-polyfill v0.1.2 (the same code running in both Firefox and Chrome) but if I update webextension-polyfill  to v0.2.1 it fails to load in Chrome due to this error:
```
chrome.clipboard is not supported on this platform or manifest version
```

> ![chrome.clipboard is not supported on this platform or manifest version](https://user-images.githubusercontent.com/157609/31631666-a88d1f18-b2ba-11e7-9fd0-f129bd4b1bd4.png)

If I remove `clipboardWrite` permission from `manifest.json` then it loads correctly in Chrome, but clipboard manipulation stops working in Firefox 🌵 

Looks like a bug, but maybe I missing something obvious here?
Let me know if I can test something or provide more debug information.

**Comment by rpl** [comment]
@lidel I've not tried to run the extension on Chrome yet, but by looking at the docs at "https://developer.chrome.com/apps/clipboard" and the last changes applied to the polyfill v0.2.1, here is what I think is happening and why:

- on chrome the clipboardWrite is an existent permission, related to the chrome.clipboard API that is described in the docs as "Dev channel only" (and also "This is a temporary solution for chromeos platform apps until open-web alternative is available.")

- on Firefox the clipboardWrite permission is required to be allowed to write to the clipboard using document.execCommand("copy") or document.execCommand("cut") (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#Clipboard_access)

For an extension that requires the clipboardWrite permission, chrome is probably defining the chrome.clipboard property as a getter that raises the above error.

In the polyfill 0.2.1 we are using `Object.assign({}, chrome)` to create a copy of the chrome object to prevent a TypeError when accessing on the polyfill an API namespace which is a read-only non-configurable property on the original chrome object.

Unfortunately this Object.assign call is likely to be the one that is triggering the chrome.clipboard getter and throwing the error.

Based on these hypothesis I'm going to create a minimal test extension that should reproduce this issue, looking a bit deeper in the issue and identify possible solutions to it.

In the meantime, here is a couple of possible workarounds that can for used from an extension which met this issue:

- temporarily lock the browser-polyfill version to the previous working version (v0.1.2)
- generate the final chrome and firefox manifest.json files from a base manifest
  (e.g. including the "applications" property and the "clipboardWrite" permission only in the Firefox manifest).
