### ISSUE TITLE
Any way to load webextension-polyfill as a module?

### ISSUE THREAD

**Issue by kirlat** [mozilla/webextension-polyfill#73]
I would like to load webextension-polyfill as a module, with import of require. Is this possible? I was not able to find any example of that. Most references I've found were loading it via manifest.json.

What I want to do is to detect whether `browser` is defined (`typeof browser === "undefined"`) in a background script. Then, depending on the result, I will decide wither to inject polyfill to a tab or not.
But, since polyfill is already loaded via manifest.json, `browser` is always defined and my approach does not work. 

My idea was to do browser support detection first, and then load polyfill as a module import, but I can't find any information anywhere about whether it is possible and how this can be done. What I've tried failed so far. Or am I approaching it in a wrong way?

**Comment by rpl** [comment]
The polyfill is build as an umd module and so you can choose to load it as a standalone script or import it using an AMD module loader or CommonJS bundler (we have also smoke tests that run on travis to ensure that the module can be used with the commonly used module bundlers, webpack and browserify: https://github.com/mozilla/webextension-polyfill/blob/master/test/run-module-bundlers-smoketests.sh).

The polyfill is released on npm (https://www.npmjs.com/package/webextension-polyfill), and so it can be included as a dependency when using a bundler on a project that has its own package.json file.

Nevertheless we should add an example of how to use it with bundlers in the project README.md (which currently mention only how to load it as a standalone script).

**Comment by kirlat** [comment]
Great, `window.browser = require('browser-polyfill');` worked like a charm and was what I wanted. I think I would not be able to figure it out myself for the life of me without your help. Many thanks!
