### ISSUE TITLE
browser.menus is undefined

### ISSUE THREAD

**Issue by Dreamsorcerer** [mozilla/webextension-polyfill#74]
browser.menus is undefined, this should presumably just alias to browser.contextMenus for compatibility.

**Comment by brettz9** [comment]
I'm getting this even in Firefox...

**Comment by brettz9** [comment]
This is particularly a problem as `browser.menus.onShown` exists but `browser.contextMenus.onShown` does not exist, so I see no way to use the polyfill and still get access to `browser.menus.onShown`. (I guess the polyfill can't add support for privileged missing features in Chrome, but it should allow for optional use, so Firefox users can take advantage of the feature.)

**Comment by Rob--W** [comment]
> I'm getting this even in Firefox... (only when using the polyfill)

To use the "browser.menus" API, the "menus" permission needs to be requested.

Extensions that use the "menus" API and permission only cannot be ported without changes, because the "contextMenus" permission has to be added to the manifest file.

If you want to build an extension for Chrome and Firefox, use the `browser.contextMenus` API. If you want to use Firefox-specific features, use the `browser.menus` API (and be aware that there is sometimes no alternative in Chrome).

**Comment by Dreamsorcerer** [comment]
But contextMenus is not part of the web extension standard. Therefore, aliasing menus to contextMenus allows a standards-compatible extension to continue working.

Understandably, the manifest will need to specify the contextMenus permission on Chrome, but that's not really an issue. I have other differences between a FF and Chrome plugin that I have to maintain anyway. Aliasing menus to contextMenus would reduce the differences needed, while still ensuring that the FF version is fully standards compliant.

**Comment by Rob--W** [comment]
The spec (which has not have much participation lately, so take it with a grain of salt) uses `browser.contextMenus`, not `browser.menus`: https://browserext.github.io/browserext/

If you do really prefer to use the `browser.menus` API over the `browser.contextMenus` API AND you don't use any `browser.menus`-specific extensions, then you could add `browser.menus = browser.menus || browser.contextMenus;` (and add `menus` and `contextMenus` permission to your manifest file).

However, if you want to minimize the number of changes that you want to maintain, then I recommend to use `browser.contextMenus` (and the `contextMenus` permission).
