### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by domoritz** [mozilla/webextension-polyfill#78]
There are typings for the callback based API at @types/chrome but not for the promise based API.

**Comment by epicgirl1998** [comment]
try [web-ext-types](https://github.com/kelseasy/web-ext-types)

it's mainly written for firefox though so things not supported by it are commented out, and it puts the types in the global scope which doesn't work nicely if you use webextension-polyfill as a module

**Comment by epicgirl1998** [comment]
as of recently there's also this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21749

the one posted above is handwritten, while this one is generated from the json schema files firefox uses

**Comment by Lusito** [comment]
I just created this project, which automatically generates typescript for webextension-polyfill from the mozilla schema files:
https://www.npmjs.com/package/webextension-polyfill-ts
https://github.com/Lusito/webextension-polyfill-ts

Please let me know what you think. This is a very early version, so help making this 100% stable is very much appreciated.

**Comment by rpl** [comment]
Closing as it is not a polyfill issue and it seems to be already covered by external projects.

**Comment by SerkanSipahi** [comment]
@Lusito thank you :)
