### ISSUE TITLE
browser.tabs.getCurrent() resolves to empty array instead of undefined

### ISSUE THREAD

**Issue by dessant** [mozilla/webextension-polyfill#81]
According to the docs browser.tabs.getCurrent() should return a promise which resolves to undefined when called from a context that has no browser tab. The API works as expected on Firefox, but resolves to an empty array on Chrome.

```js
browser.tabs.getCurrent().then(function(tab) {
    console.log(1, tab);
  })
chrome.tabs.getCurrent(function(tab) {
  console.log(2, tab);
});
```

Firefox background or popup script:
```js
1 undefined
2 undefined
```

Chrome background or popup script:
```js
1 Array(0)
2 undefined
```

**Comment by andymckay** [comment]
Is this a bug in the polyfill library or a bug in Firefox? If its a bug in Firefox it should go into Bugzilla rather than here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=WebExtensions:%20Untriaged

**Comment by dessant** [comment]
Polyfill.
