### ISSUE TITLE
browser.webRequest.onAuthRequired.addListener does not accept Promises on chrome

### ISSUE THREAD

**Issue by Asgraf** [mozilla/webextension-polyfill#91]
Chrome does not support Promises in and uses callback function instead so the code below will not work on chrome
````js
browser.webRequest.onAuthRequired.addListener(
	someCallbackFunctionThatReturnsPromise,
	{urls: ['<all_urls>']},
	['blocking']
);
````
browser.webRequest.onAuthRequired.addListener should rewrite 'blocking' into 'asyncBlocking' and call chrome's callback function when provided Promise is resolved.

**Comment by Rob--W** [comment]
I've been told that Chrome is open to supporting promises as return values. If anyone submits a patch that adds promise support to Chrome's webRequest API, then it would seriously be considered.

Currently, `onAuthRequired` is the only webRequest API that supports an asynchronous resolution in Chrome. In contrast, Firefox supports asynchronous results in every webRequest event. An extension that makes heavy use of asynchronous webRequest events can likely not function in Chrome at the moment. For consistency with other events (and also considering the eventual possibility of having asynchronous webRequest events in Chrome), we will not polyfill the `webRequest.onAuthRequired` event.

**Comment by slhck** [comment]
Chrome has recently [changed this](https://developer.chrome.com/docs/extensions/reference/webRequest/):

> As of Chrome 108, you can asynchronously supply credentials for [onAuthRequired events](https://developer.chrome.com/docs/extensions/reference/webRequest/#event-onAuthRequired) if you use the "webRequest" and "webRequestAuthProvider" permissions.

Could this be reconsidered?

**Comment by Rob--W** [comment]
> Chrome has recently [changed this](https://developer.chrome.com/docs/extensions/reference/webRequest/):
> 
> > As of Chrome 108, you can asynchronously supply credentials for [onAuthRequired events](https://developer.chrome.com/docs/extensions/reference/webRequest/#event-onAuthRequired) if you use the "webRequest" and "webRequestAuthProvider" permissions.
> 
> Could this be reconsidered? (Or am I misunderstanding this issue?)

This does not change my position. The "webRequestAuthProvider" permission was introduced as a replacement for webRequestBlocking in Chrome's Manifest Version 3.
