### ISSUE TITLE
Deferred.resolve not passing data... Works in chrome.

### ISSUE THREAD

**Issue by PCSmith** [mozilla/webextension-polyfill#95]
**Extension pop up window sends message requesting important info:**
```
let Params = { Event: 'CreateNewPostInit' };

browser.runtime.sendMessage(Params).then(function (response) {
	console.log(response.ImportantInfo);
});
```

**Background page receives:**
```
browser.runtime.onMessage.addListener(GotMessage);

function GotMessage(request, sender) {
	var defd = null;

	switch (request.Event) {
		case "CreateNewPostInit":
			defd = $.Deferred();
			CreateNewPostInit(request, sender, defd);
			return defd.promise();
			break;
	}
}

function CreateNewPostInit(request, sender, defd) {
	defd.resolve({ ImportantInfo: "42" });
}
```

In Chrome "42" is logged to the console from the line in the then after the sendMessage. Firefox throws a "TypeError: response is undefined".

Thanks for the assistance in advance.

**Comment by Rob--W** [comment]
Firefox expects a real promise, from the same scope of the script (i.e. `Promise` created in a different execution context such as a child frame or popup won't work), whereas the polyfill accepts any thenable (object with a `then` method).

Don't use jQuery's `Deferred`, use native promises instead.

**Comment by PCSmith** [comment]
Thanks for the info -- I thought the defd.promise() returned an actual promise or at least something that could be cast to one... Is that not the case for this?

**Comment by Euregan** [comment]
Just wanted to point out that Chrome seems to wrap the return in a Promise by default, while Firefox simply resolves to undefined. Works like a charm when wrapping the return in a Promise though.

**Comment by Rob--W** [comment]
In Firefox, the polyfill doesn't do anything since the `browser` object already exists. In Chrome, the polyfill aims to mimic the promise-based `browser` API that Firefox supports.

`defd.promise` from jQuery is not a real promise. It is a thenable.

**Comment by Rob--W** [comment]
We will document more clearly that the polyfill does not do anything in Firefox (#55).
To fix this specific bug, real promises should be used instead of thenables.
