### ISSUE TITLE
Uncaught ReferenceError: module is not defined at browser-polyfill.js:363

### ISSUE THREAD

**Issue by gbosetti** [mozilla/webextension-polyfill#96]
Guys, I just added the library in my extension for using it from a background script from chrome. I added a first line before importing the browser-polyfill.js file, since there is no browser object in chrome:
`browser = (window.chrome)? window.chrome : browser;
`
But then, I am receiving the following error:
Uncaught ReferenceError: module is not defined at browser-polyfill.js:363

How can I solve this? Is anything extra that I should do before importing the file?
Thanks in advance

**Comment by rpl** [comment]
@gbosetti the `browser = (window.chrome)? window.chrome : browser;` line is not something that should be needed, the polyfill detects that there is no `browser` global defined and defines it with the API namespaces wrapped by the polyfill (here: https://github.com/mozilla/webextension-polyfill/blob/0fd508671aad4b9530b22f612871bdb58c363c40/src/browser-polyfill.js#L9).

Can you attach in a comment or upload somewhere a small test extension that reproduce your issue?
Based on the error message it seems that the polyfill is not being included correctly, but a test extension would be helpful to provide you more details of the ones already mentioned in the readme file.
